//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriskisSvettisLib.DefendoWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResultBase", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.StartSessionResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.GetInstructorsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.GetLocationsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.GetActivityFormsAndTypesResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.GetSchemaWithFilterResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.GetBookingDataWithFilterResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.GetDatedActivityByIdResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.RegisterUserResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.LoginUserResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.LogoutUserResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.ChangePasswordResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.ForgotPasswordResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.GetPersonInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.UpdatePersonInfoResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.GetSchemaResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.GetBookingDataResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.BookResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.CancelBookingResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.GetOrganisationsResult))]
    public partial class ResultBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.ErrorLevel ErrorLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.ErrorLevel ErrorLevel {
            get {
                return this.ErrorLevelField;
            }
            set {
                if ((this.ErrorLevelField.Equals(value) != true)) {
                    this.ErrorLevelField = value;
                    this.RaisePropertyChanged("ErrorLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StartSessionResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class StartSessionResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Session SessionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Session Session {
            get {
                return this.SessionField;
            }
            set {
                if ((object.ReferenceEquals(this.SessionField, value) != true)) {
                    this.SessionField = value;
                    this.RaisePropertyChanged("Session");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetInstructorsResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class GetInstructorsResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Instructor[] InstructorsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Instructor[] Instructors {
            get {
                return this.InstructorsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorsField, value) != true)) {
                    this.InstructorsField = value;
                    this.RaisePropertyChanged("Instructors");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLocationsResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class GetLocationsResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Location[] LocationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Location[] Locations {
            get {
                return this.LocationsField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationsField, value) != true)) {
                    this.LocationsField = value;
                    this.RaisePropertyChanged("Locations");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetActivityFormsAndTypesResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class GetActivityFormsAndTypesResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.ActivityForm[] ActivityFormsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.ActivityForm[] ActivityForms {
            get {
                return this.ActivityFormsField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityFormsField, value) != true)) {
                    this.ActivityFormsField = value;
                    this.RaisePropertyChanged("ActivityForms");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSchemaWithFilterResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class GetSchemaWithFilterResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.DatedActivity[] DatedActivitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.DatedActivity[] DatedActivities {
            get {
                return this.DatedActivitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.DatedActivitiesField, value) != true)) {
                    this.DatedActivitiesField = value;
                    this.RaisePropertyChanged("DatedActivities");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBookingDataWithFilterResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class GetBookingDataWithFilterResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.BookableDatedActivity[] BookableActivitesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.BookedDatedActivity[] BookedActivitesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Text BookingRuleDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.MissedDatedActivity[] MissedBookedActivitesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.BookableDatedActivity[] BookableActivites {
            get {
                return this.BookableActivitesField;
            }
            set {
                if ((object.ReferenceEquals(this.BookableActivitesField, value) != true)) {
                    this.BookableActivitesField = value;
                    this.RaisePropertyChanged("BookableActivites");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.BookedDatedActivity[] BookedActivites {
            get {
                return this.BookedActivitesField;
            }
            set {
                if ((object.ReferenceEquals(this.BookedActivitesField, value) != true)) {
                    this.BookedActivitesField = value;
                    this.RaisePropertyChanged("BookedActivites");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Text BookingRuleDescription {
            get {
                return this.BookingRuleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingRuleDescriptionField, value) != true)) {
                    this.BookingRuleDescriptionField = value;
                    this.RaisePropertyChanged("BookingRuleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.MissedDatedActivity[] MissedBookedActivites {
            get {
                return this.MissedBookedActivitesField;
            }
            set {
                if ((object.ReferenceEquals(this.MissedBookedActivitesField, value) != true)) {
                    this.MissedBookedActivitesField = value;
                    this.RaisePropertyChanged("MissedBookedActivites");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDatedActivityByIdResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class GetDatedActivityByIdResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.BookableDatedActivity BookableActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.BookedDatedActivity BookedActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.DatedActivity DatedActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.MissedDatedActivity MissedBookedActivityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.BookableDatedActivity BookableActivity {
            get {
                return this.BookableActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.BookableActivityField, value) != true)) {
                    this.BookableActivityField = value;
                    this.RaisePropertyChanged("BookableActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.BookedDatedActivity BookedActivity {
            get {
                return this.BookedActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.BookedActivityField, value) != true)) {
                    this.BookedActivityField = value;
                    this.RaisePropertyChanged("BookedActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.DatedActivity DatedActivity {
            get {
                return this.DatedActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.DatedActivityField, value) != true)) {
                    this.DatedActivityField = value;
                    this.RaisePropertyChanged("DatedActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.MissedDatedActivity MissedBookedActivity {
            get {
                return this.MissedBookedActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.MissedBookedActivityField, value) != true)) {
                    this.MissedBookedActivityField = value;
                    this.RaisePropertyChanged("MissedBookedActivity");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterUserResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class RegisterUserResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool MailSentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool MailSent {
            get {
                return this.MailSentField;
            }
            set {
                if ((this.MailSentField.Equals(value) != true)) {
                    this.MailSentField = value;
                    this.RaisePropertyChanged("MailSent");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginUserResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class LoginUserResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.LoginToken TokenField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.LoginToken Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogoutUserResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class LogoutUserResult : FriskisSvettisLib.DefendoWebService.ResultBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ChangePasswordResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class ChangePasswordResult : FriskisSvettisLib.DefendoWebService.ResultBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ForgotPasswordResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class ForgotPasswordResult : FriskisSvettisLib.DefendoWebService.ResultBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetPersonInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class GetPersonInfoResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Person PersonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Person Person {
            get {
                return this.PersonField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonField, value) != true)) {
                    this.PersonField = value;
                    this.RaisePropertyChanged("Person");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdatePersonInfoResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class UpdatePersonInfoResult : FriskisSvettisLib.DefendoWebService.ResultBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetSchemaResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class GetSchemaResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.DatedActivity[] DatedActivitiesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.DatedActivity[] DatedActivities {
            get {
                return this.DatedActivitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.DatedActivitiesField, value) != true)) {
                    this.DatedActivitiesField = value;
                    this.RaisePropertyChanged("DatedActivities");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBookingDataResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class GetBookingDataResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.BookableDatedActivity[] BookableActivitesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.BookedDatedActivity[] BookedActivitesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Text BookingRuleDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.MissedDatedActivity[] MissedBookedActivitesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.BookableDatedActivity[] BookableActivites {
            get {
                return this.BookableActivitesField;
            }
            set {
                if ((object.ReferenceEquals(this.BookableActivitesField, value) != true)) {
                    this.BookableActivitesField = value;
                    this.RaisePropertyChanged("BookableActivites");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.BookedDatedActivity[] BookedActivites {
            get {
                return this.BookedActivitesField;
            }
            set {
                if ((object.ReferenceEquals(this.BookedActivitesField, value) != true)) {
                    this.BookedActivitesField = value;
                    this.RaisePropertyChanged("BookedActivites");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Text BookingRuleDescription {
            get {
                return this.BookingRuleDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.BookingRuleDescriptionField, value) != true)) {
                    this.BookingRuleDescriptionField = value;
                    this.RaisePropertyChanged("BookingRuleDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.MissedDatedActivity[] MissedBookedActivites {
            get {
                return this.MissedBookedActivitesField;
            }
            set {
                if ((object.ReferenceEquals(this.MissedBookedActivitesField, value) != true)) {
                    this.MissedBookedActivitesField = value;
                    this.RaisePropertyChanged("MissedBookedActivites");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class BookResult : FriskisSvettisLib.DefendoWebService.ResultBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelBookingResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class CancelBookingResult : FriskisSvettisLib.DefendoWebService.ResultBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOrganisationsResult", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class GetOrganisationsResult : FriskisSvettisLib.DefendoWebService.ResultBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Organisation[] OrganisationsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Organisation[] Organisations {
            get {
                return this.OrganisationsField;
            }
            set {
                if ((object.ReferenceEquals(this.OrganisationsField, value) != true)) {
                    this.OrganisationsField = value;
                    this.RaisePropertyChanged("Organisations");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ErrorLevel", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    public enum ErrorLevel : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrganisationMissingLicense = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UserNotFound = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidOldPassword = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEmailFormat = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidOrganisation = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidCountry = 150,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidContext = 160,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SessionExpired = 200,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LoginTokenExpired = 210,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CantBook_AlreadyBooked = 220,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CantBook_MissingDopingAgreement = 223,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CantBook_NoSpotsLeft = 224,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CantBook_MissedToMany = 225,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CantCancelBooking_NotBooked = 231,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UsernameInUse = 240,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PersonNotFound = 241,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WeakPassword = 242,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TermsOfUseNotAccepted = 243,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLicense = 300,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidSession = 310,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidLoginToken = 320,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidStartDate = 340,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidEndDate = 345,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvalidDatedActivity = 370,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CriticalServerError = 505,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organisation", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class Organisation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomepageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Homepage {
            get {
                return this.HomepageField;
            }
            set {
                if ((object.ReferenceEquals(this.HomepageField, value) != true)) {
                    this.HomepageField = value;
                    this.RaisePropertyChanged("Homepage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Session", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class Session : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        private byte[] KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Instructor", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class Instructor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityForm", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class ActivityForm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.ActivityType[] ActivityTypesField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.ActivityType[] ActivityTypes {
            get {
                return this.ActivityTypesField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityTypesField, value) != true)) {
                    this.ActivityTypesField = value;
                    this.RaisePropertyChanged("ActivityTypes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityType", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class ActivityType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatedActivity", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class DatedActivity : FriskisSvettisLib.DefendoWebService.DatedActivityBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DatedActivityBase", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.BookableDatedActivity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.BookedDatedActivity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.MissedDatedActivity))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.DatedActivity))]
    public partial class DatedActivityBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CurrentBookedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Text DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Text HostsField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Text InstructorsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCancelledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDropInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOnceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Text LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxBookableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxParticipantsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool RequiresDopingAgreementField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrentBooked {
            get {
                return this.CurrentBookedField;
            }
            set {
                if ((this.CurrentBookedField.Equals(value) != true)) {
                    this.CurrentBookedField = value;
                    this.RaisePropertyChanged("CurrentBooked");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Text Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Ends {
            get {
                return this.EndsField;
            }
            set {
                if ((this.EndsField.Equals(value) != true)) {
                    this.EndsField = value;
                    this.RaisePropertyChanged("Ends");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Text Hosts {
            get {
                return this.HostsField;
            }
            set {
                if ((object.ReferenceEquals(this.HostsField, value) != true)) {
                    this.HostsField = value;
                    this.RaisePropertyChanged("Hosts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Text Instructors {
            get {
                return this.InstructorsField;
            }
            set {
                if ((object.ReferenceEquals(this.InstructorsField, value) != true)) {
                    this.InstructorsField = value;
                    this.RaisePropertyChanged("Instructors");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCancelled {
            get {
                return this.IsCancelledField;
            }
            set {
                if ((this.IsCancelledField.Equals(value) != true)) {
                    this.IsCancelledField = value;
                    this.RaisePropertyChanged("IsCancelled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDropIn {
            get {
                return this.IsDropInField;
            }
            set {
                if ((this.IsDropInField.Equals(value) != true)) {
                    this.IsDropInField = value;
                    this.RaisePropertyChanged("IsDropIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFree {
            get {
                return this.IsFreeField;
            }
            set {
                if ((this.IsFreeField.Equals(value) != true)) {
                    this.IsFreeField = value;
                    this.RaisePropertyChanged("IsFree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOnce {
            get {
                return this.IsOnceField;
            }
            set {
                if ((this.IsOnceField.Equals(value) != true)) {
                    this.IsOnceField = value;
                    this.RaisePropertyChanged("IsOnce");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Text Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxBookable {
            get {
                return this.MaxBookableField;
            }
            set {
                if ((this.MaxBookableField.Equals(value) != true)) {
                    this.MaxBookableField = value;
                    this.RaisePropertyChanged("MaxBookable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxParticipants {
            get {
                return this.MaxParticipantsField;
            }
            set {
                if ((this.MaxParticipantsField.Equals(value) != true)) {
                    this.MaxParticipantsField = value;
                    this.RaisePropertyChanged("MaxParticipants");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool RequiresDopingAgreement {
            get {
                return this.RequiresDopingAgreementField;
            }
            set {
                if ((this.RequiresDopingAgreementField.Equals(value) != true)) {
                    this.RequiresDopingAgreementField = value;
                    this.RaisePropertyChanged("RequiresDopingAgreement");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Starts {
            get {
                return this.StartsField;
            }
            set {
                if ((this.StartsField.Equals(value) != true)) {
                    this.StartsField = value;
                    this.RaisePropertyChanged("Starts");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Text", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class Text : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HtmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlainField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Html {
            get {
                return this.HtmlField;
            }
            set {
                if ((object.ReferenceEquals(this.HtmlField, value) != true)) {
                    this.HtmlField = value;
                    this.RaisePropertyChanged("Html");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Plain {
            get {
                return this.PlainField;
            }
            set {
                if ((object.ReferenceEquals(this.PlainField, value) != true)) {
                    this.PlainField = value;
                    this.RaisePropertyChanged("Plain");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookableDatedActivity", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FriskisSvettisLib.DefendoWebService.BookedDatedActivity))]
    public partial class BookableDatedActivity : FriskisSvettisLib.DefendoWebService.DatedActivityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BookingStartsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> BookingStopsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CancelBookingStopsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckInEndsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckInStartsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BookingStarts {
            get {
                return this.BookingStartsField;
            }
            set {
                if ((this.BookingStartsField.Equals(value) != true)) {
                    this.BookingStartsField = value;
                    this.RaisePropertyChanged("BookingStarts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BookingStops {
            get {
                return this.BookingStopsField;
            }
            set {
                if ((this.BookingStopsField.Equals(value) != true)) {
                    this.BookingStopsField = value;
                    this.RaisePropertyChanged("BookingStops");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CancelBookingStops {
            get {
                return this.CancelBookingStopsField;
            }
            set {
                if ((this.CancelBookingStopsField.Equals(value) != true)) {
                    this.CancelBookingStopsField = value;
                    this.RaisePropertyChanged("CancelBookingStops");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckInEnds {
            get {
                return this.CheckInEndsField;
            }
            set {
                if ((this.CheckInEndsField.Equals(value) != true)) {
                    this.CheckInEndsField = value;
                    this.RaisePropertyChanged("CheckInEnds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckInStarts {
            get {
                return this.CheckInStartsField;
            }
            set {
                if ((this.CheckInStartsField.Equals(value) != true)) {
                    this.CheckInStartsField = value;
                    this.RaisePropertyChanged("CheckInStarts");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookedDatedActivity", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class BookedDatedActivity : FriskisSvettisLib.DefendoWebService.BookableDatedActivity {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid BookingIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid BookingId {
            get {
                return this.BookingIdField;
            }
            set {
                if ((this.BookingIdField.Equals(value) != true)) {
                    this.BookingIdField = value;
                    this.RaisePropertyChanged("BookingId");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MissedDatedActivity", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class MissedDatedActivity : FriskisSvettisLib.DefendoWebService.DatedActivityBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.MissReason ReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.MissReason Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((this.ReasonField.Equals(value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MissReason", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    public enum MissReason : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotShowedUp = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CancelledTooLate = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LoginToken", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class LoginToken : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private byte[] KeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte[] Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AcceptsEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FriskisSvettisLib.DefendoWebService.Gender GenderField;
        
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MemberNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrimaryEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondaryEmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AcceptsEmail {
            get {
                return this.AcceptsEmailField;
            }
            set {
                if ((this.AcceptsEmailField.Equals(value) != true)) {
                    this.AcceptsEmailField = value;
                    this.RaisePropertyChanged("AcceptsEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Firstname {
            get {
                return this.FirstnameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstnameField, value) != true)) {
                    this.FirstnameField = value;
                    this.RaisePropertyChanged("Firstname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FriskisSvettisLib.DefendoWebService.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lastname {
            get {
                return this.LastnameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastnameField, value) != true)) {
                    this.LastnameField = value;
                    this.RaisePropertyChanged("Lastname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MemberNumber {
            get {
                return this.MemberNumberField;
            }
            set {
                if ((this.MemberNumberField.Equals(value) != true)) {
                    this.MemberNumberField = value;
                    this.RaisePropertyChanged("MemberNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrimaryEmail {
            get {
                return this.PrimaryEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.PrimaryEmailField, value) != true)) {
                    this.PrimaryEmailField = value;
                    this.RaisePropertyChanged("PrimaryEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondaryEmail {
            get {
                return this.SecondaryEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondaryEmailField, value) != true)) {
                    this.SecondaryEmailField = value;
                    this.RaisePropertyChanged("SecondaryEmail");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/Jympa.BookingService")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DefendoWebService.IBookingService", SessionMode=System.ServiceModel.SessionMode.NotAllowed)]
    public interface IBookingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetOrganisations", ReplyAction="http://tempuri.org/IBookingService/GetOrganisationsResponse")]
        FriskisSvettisLib.DefendoWebService.GetOrganisationsResult GetOrganisations(string country, System.Guid contextId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/StartSession", ReplyAction="http://tempuri.org/IBookingService/StartSessionResponse")]
        FriskisSvettisLib.DefendoWebService.StartSessionResult StartSession(string license, FriskisSvettisLib.DefendoWebService.Organisation organisation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetInstructors", ReplyAction="http://tempuri.org/IBookingService/GetInstructorsResponse")]
        FriskisSvettisLib.DefendoWebService.GetInstructorsResult GetInstructors(FriskisSvettisLib.DefendoWebService.Session session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetLocations", ReplyAction="http://tempuri.org/IBookingService/GetLocationsResponse")]
        FriskisSvettisLib.DefendoWebService.GetLocationsResult GetLocations(FriskisSvettisLib.DefendoWebService.Session session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetActivityFormsAndTypes", ReplyAction="http://tempuri.org/IBookingService/GetActivityFormsAndTypesResponse")]
        FriskisSvettisLib.DefendoWebService.GetActivityFormsAndTypesResult GetActivityFormsAndTypes(FriskisSvettisLib.DefendoWebService.Session session);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetSchemaWithFilter", ReplyAction="http://tempuri.org/IBookingService/GetSchemaWithFilterResponse")]
        FriskisSvettisLib.DefendoWebService.GetSchemaWithFilterResult GetSchemaWithFilter(FriskisSvettisLib.DefendoWebService.Session session, System.DateTime start, System.DateTime end, FriskisSvettisLib.DefendoWebService.Location location, FriskisSvettisLib.DefendoWebService.ActivityForm activityForm, FriskisSvettisLib.DefendoWebService.ActivityType activityType, FriskisSvettisLib.DefendoWebService.Instructor instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetBookingDataWithFilter", ReplyAction="http://tempuri.org/IBookingService/GetBookingDataWithFilterResponse")]
        FriskisSvettisLib.DefendoWebService.GetBookingDataWithFilterResult GetBookingDataWithFilter(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end, FriskisSvettisLib.DefendoWebService.Location location, FriskisSvettisLib.DefendoWebService.ActivityForm activityForm, FriskisSvettisLib.DefendoWebService.ActivityType activityType, FriskisSvettisLib.DefendoWebService.Instructor instructor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetDatedActivityById", ReplyAction="http://tempuri.org/IBookingService/GetDatedActivityByIdResponse")]
        FriskisSvettisLib.DefendoWebService.GetDatedActivityByIdResult GetDatedActivityById(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/RegisterUser", ReplyAction="http://tempuri.org/IBookingService/RegisterUserResponse")]
        FriskisSvettisLib.DefendoWebService.RegisterUserResult RegisterUser(FriskisSvettisLib.DefendoWebService.Session session, int memberNumber, string firstname, string lastname, string email, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/LoginUser", ReplyAction="http://tempuri.org/IBookingService/LoginUserResponse")]
        FriskisSvettisLib.DefendoWebService.LoginUserResult LoginUser(FriskisSvettisLib.DefendoWebService.Session session, string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/LogoutUser", ReplyAction="http://tempuri.org/IBookingService/LogoutUserResponse")]
        FriskisSvettisLib.DefendoWebService.LogoutUserResult LogoutUser(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/ChangePassword", ReplyAction="http://tempuri.org/IBookingService/ChangePasswordResponse")]
        FriskisSvettisLib.DefendoWebService.ChangePasswordResult ChangePassword(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/ForgotPassword", ReplyAction="http://tempuri.org/IBookingService/ForgotPasswordResponse")]
        FriskisSvettisLib.DefendoWebService.ForgotPasswordResult ForgotPassword(FriskisSvettisLib.DefendoWebService.Session session, string identifier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetPersonInfo", ReplyAction="http://tempuri.org/IBookingService/GetPersonInfoResponse")]
        FriskisSvettisLib.DefendoWebService.GetPersonInfoResult GetPersonInfo(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/UpdatePersonInfo", ReplyAction="http://tempuri.org/IBookingService/UpdatePersonInfoResponse")]
        FriskisSvettisLib.DefendoWebService.UpdatePersonInfoResult UpdatePersonInfo(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, FriskisSvettisLib.DefendoWebService.Gender gender, string firstname, string lastname, string primaryEmail, string secondaryEmail, bool acceptsEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetSchema", ReplyAction="http://tempuri.org/IBookingService/GetSchemaResponse")]
        FriskisSvettisLib.DefendoWebService.GetSchemaResult GetSchema(FriskisSvettisLib.DefendoWebService.Session session, System.DateTime start, System.DateTime end);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/GetBookingData", ReplyAction="http://tempuri.org/IBookingService/GetBookingDataResponse")]
        FriskisSvettisLib.DefendoWebService.GetBookingDataResult GetBookingData(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/Book", ReplyAction="http://tempuri.org/IBookingService/BookResponse")]
        FriskisSvettisLib.DefendoWebService.BookResult Book(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, FriskisSvettisLib.DefendoWebService.BookableDatedActivity datedActivity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBookingService/CancelBooking", ReplyAction="http://tempuri.org/IBookingService/CancelBookingResponse")]
        FriskisSvettisLib.DefendoWebService.CancelBookingResult CancelBooking(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, FriskisSvettisLib.DefendoWebService.BookedDatedActivity datedActivity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBookingServiceChannel : FriskisSvettisLib.DefendoWebService.IBookingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookingServiceClient : System.ServiceModel.ClientBase<FriskisSvettisLib.DefendoWebService.IBookingService>, FriskisSvettisLib.DefendoWebService.IBookingService {
        
        public BookingServiceClient() {
        }
        
        public BookingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FriskisSvettisLib.DefendoWebService.GetOrganisationsResult GetOrganisations(string country, System.Guid contextId) {
            return base.Channel.GetOrganisations(country, contextId);
        }
        
        public FriskisSvettisLib.DefendoWebService.StartSessionResult StartSession(string license, FriskisSvettisLib.DefendoWebService.Organisation organisation) {
            return base.Channel.StartSession(license, organisation);
        }
        
        public FriskisSvettisLib.DefendoWebService.GetInstructorsResult GetInstructors(FriskisSvettisLib.DefendoWebService.Session session) {
            return base.Channel.GetInstructors(session);
        }
        
        public FriskisSvettisLib.DefendoWebService.GetLocationsResult GetLocations(FriskisSvettisLib.DefendoWebService.Session session) {
            return base.Channel.GetLocations(session);
        }
        
        public FriskisSvettisLib.DefendoWebService.GetActivityFormsAndTypesResult GetActivityFormsAndTypes(FriskisSvettisLib.DefendoWebService.Session session) {
            return base.Channel.GetActivityFormsAndTypes(session);
        }
        
        public FriskisSvettisLib.DefendoWebService.GetSchemaWithFilterResult GetSchemaWithFilter(FriskisSvettisLib.DefendoWebService.Session session, System.DateTime start, System.DateTime end, FriskisSvettisLib.DefendoWebService.Location location, FriskisSvettisLib.DefendoWebService.ActivityForm activityForm, FriskisSvettisLib.DefendoWebService.ActivityType activityType, FriskisSvettisLib.DefendoWebService.Instructor instructor) {
            return base.Channel.GetSchemaWithFilter(session, start, end, location, activityForm, activityType, instructor);
        }
        
        public FriskisSvettisLib.DefendoWebService.GetBookingDataWithFilterResult GetBookingDataWithFilter(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, System.Nullable<System.DateTime> start, System.Nullable<System.DateTime> end, FriskisSvettisLib.DefendoWebService.Location location, FriskisSvettisLib.DefendoWebService.ActivityForm activityForm, FriskisSvettisLib.DefendoWebService.ActivityType activityType, FriskisSvettisLib.DefendoWebService.Instructor instructor) {
            return base.Channel.GetBookingDataWithFilter(session, token, start, end, location, activityForm, activityType, instructor);
        }
        
        public FriskisSvettisLib.DefendoWebService.GetDatedActivityByIdResult GetDatedActivityById(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, System.Guid id) {
            return base.Channel.GetDatedActivityById(session, token, id);
        }
        
        public FriskisSvettisLib.DefendoWebService.RegisterUserResult RegisterUser(FriskisSvettisLib.DefendoWebService.Session session, int memberNumber, string firstname, string lastname, string email, string username, string password) {
            return base.Channel.RegisterUser(session, memberNumber, firstname, lastname, email, username, password);
        }
        
        public FriskisSvettisLib.DefendoWebService.LoginUserResult LoginUser(FriskisSvettisLib.DefendoWebService.Session session, string username, string password) {
            return base.Channel.LoginUser(session, username, password);
        }
        
        public FriskisSvettisLib.DefendoWebService.LogoutUserResult LogoutUser(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token) {
            return base.Channel.LogoutUser(session, token);
        }
        
        public FriskisSvettisLib.DefendoWebService.ChangePasswordResult ChangePassword(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, string oldPassword, string newPassword) {
            return base.Channel.ChangePassword(session, token, oldPassword, newPassword);
        }
        
        public FriskisSvettisLib.DefendoWebService.ForgotPasswordResult ForgotPassword(FriskisSvettisLib.DefendoWebService.Session session, string identifier) {
            return base.Channel.ForgotPassword(session, identifier);
        }
        
        public FriskisSvettisLib.DefendoWebService.GetPersonInfoResult GetPersonInfo(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token) {
            return base.Channel.GetPersonInfo(session, token);
        }
        
        public FriskisSvettisLib.DefendoWebService.UpdatePersonInfoResult UpdatePersonInfo(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, FriskisSvettisLib.DefendoWebService.Gender gender, string firstname, string lastname, string primaryEmail, string secondaryEmail, bool acceptsEmail) {
            return base.Channel.UpdatePersonInfo(session, token, gender, firstname, lastname, primaryEmail, secondaryEmail, acceptsEmail);
        }
        
        public FriskisSvettisLib.DefendoWebService.GetSchemaResult GetSchema(FriskisSvettisLib.DefendoWebService.Session session, System.DateTime start, System.DateTime end) {
            return base.Channel.GetSchema(session, start, end);
        }
        
        public FriskisSvettisLib.DefendoWebService.GetBookingDataResult GetBookingData(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token) {
            return base.Channel.GetBookingData(session, token);
        }
        
        public FriskisSvettisLib.DefendoWebService.BookResult Book(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, FriskisSvettisLib.DefendoWebService.BookableDatedActivity datedActivity) {
            return base.Channel.Book(session, token, datedActivity);
        }
        
        public FriskisSvettisLib.DefendoWebService.CancelBookingResult CancelBooking(FriskisSvettisLib.DefendoWebService.Session session, FriskisSvettisLib.DefendoWebService.LoginToken token, FriskisSvettisLib.DefendoWebService.BookedDatedActivity datedActivity) {
            return base.Channel.CancelBooking(session, token, datedActivity);
        }
    }
}
