//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
// 
#pragma warning disable 1591

namespace FriskisSvettisLib.DLService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IDlp2wsRR_Extbinding", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TRRLanguage))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TRRClass))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TInstructorCode))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TObjectClassCode))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TRRObjectCLass))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TRRObjectCard))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TRRInstructor))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TLocationCode))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TRRSpace))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TRRObject))]
    public partial class IDlp2wsRR_Extservice : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetObjectListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSpaceListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLocationListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetInstructorsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CustomerLoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerRightsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetObjectClassListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerClassCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerReservationsOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakeReservationOperationCompleted;
        
        private System.Threading.SendOrPostCallback MakeRsvToQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelQueueOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetClassesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTimeZoneInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLanguagesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetWebTextOperationCompleted;
        
        private System.Threading.SendOrPostCallback DummyOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public IDlp2wsRR_Extservice() {
            this.Url = global::FriskisSvettisLib.Properties.Settings.Default.FriskisSvettisLib_DLService_IDlp2wsRR_Extservice;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetObjectListCompletedEventHandler GetObjectListCompleted;
        
        /// <remarks/>
        public event GetSpaceListCompletedEventHandler GetSpaceListCompleted;
        
        /// <remarks/>
        public event GetLocationListCompletedEventHandler GetLocationListCompleted;
        
        /// <remarks/>
        public event GetInstructorsCompletedEventHandler GetInstructorsCompleted;
        
        /// <remarks/>
        public event CustomerLoginCompletedEventHandler CustomerLoginCompleted;
        
        /// <remarks/>
        public event GetCustomerInfoCompletedEventHandler GetCustomerInfoCompleted;
        
        /// <remarks/>
        public event GetCustomerRightsCompletedEventHandler GetCustomerRightsCompleted;
        
        /// <remarks/>
        public event GetObjectClassListCompletedEventHandler GetObjectClassListCompleted;
        
        /// <remarks/>
        public event GetCustomerClassCodeCompletedEventHandler GetCustomerClassCodeCompleted;
        
        /// <remarks/>
        public event GetCustomerReservationsCompletedEventHandler GetCustomerReservationsCompleted;
        
        /// <remarks/>
        public event CancelReservationCompletedEventHandler CancelReservationCompleted;
        
        /// <remarks/>
        public event MakeReservationCompletedEventHandler MakeReservationCompleted;
        
        /// <remarks/>
        public event MakeRsvToQueueCompletedEventHandler MakeRsvToQueueCompleted;
        
        /// <remarks/>
        public event CancelQueueCompletedEventHandler CancelQueueCompleted;
        
        /// <remarks/>
        public event GetClassesCompletedEventHandler GetClassesCompleted;
        
        /// <remarks/>
        public event GetTimeZoneInfoCompletedEventHandler GetTimeZoneInfoCompleted;
        
        /// <remarks/>
        public event GetLanguagesCompletedEventHandler GetLanguagesCompleted;
        
        /// <remarks/>
        public event GetWebTextCompletedEventHandler GetWebTextCompleted;
        
        /// <remarks/>
        public event DummyCompletedEventHandler DummyCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetObjectList", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetObjectList(string ObjectType, int Language, ref TRRObject[] ArrObject) {
            object[] results = this.Invoke("GetObjectList", new object[] {
                        ObjectType,
                        Language,
                        ArrObject});
            ArrObject = ((TRRObject[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetObjectListAsync(string ObjectType, int Language, TRRObject[] ArrObject) {
            this.GetObjectListAsync(ObjectType, Language, ArrObject, null);
        }
        
        /// <remarks/>
        public void GetObjectListAsync(string ObjectType, int Language, TRRObject[] ArrObject, object userState) {
            if ((this.GetObjectListOperationCompleted == null)) {
                this.GetObjectListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetObjectListOperationCompleted);
            }
            this.InvokeAsync("GetObjectList", new object[] {
                        ObjectType,
                        Language,
                        ArrObject}, this.GetObjectListOperationCompleted, userState);
        }
        
        private void OnGetObjectListOperationCompleted(object arg) {
            if ((this.GetObjectListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetObjectListCompleted(this, new GetObjectListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetSpaceList", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetSpaceList(int Language, ref TRRSpace[] ArrSpace) {
            object[] results = this.Invoke("GetSpaceList", new object[] {
                        Language,
                        ArrSpace});
            ArrSpace = ((TRRSpace[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetSpaceListAsync(int Language, TRRSpace[] ArrSpace) {
            this.GetSpaceListAsync(Language, ArrSpace, null);
        }
        
        /// <remarks/>
        public void GetSpaceListAsync(int Language, TRRSpace[] ArrSpace, object userState) {
            if ((this.GetSpaceListOperationCompleted == null)) {
                this.GetSpaceListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSpaceListOperationCompleted);
            }
            this.InvokeAsync("GetSpaceList", new object[] {
                        Language,
                        ArrSpace}, this.GetSpaceListOperationCompleted, userState);
        }
        
        private void OnGetSpaceListOperationCompleted(object arg) {
            if ((this.GetSpaceListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSpaceListCompleted(this, new GetSpaceListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetLocationList", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetLocationList(int Language, ref TLocation[] Arrlocation) {
            object[] results = this.Invoke("GetLocationList", new object[] {
                        Language,
                        Arrlocation});
            Arrlocation = ((TLocation[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetLocationListAsync(int Language, TLocation[] Arrlocation) {
            this.GetLocationListAsync(Language, Arrlocation, null);
        }
        
        /// <remarks/>
        public void GetLocationListAsync(int Language, TLocation[] Arrlocation, object userState) {
            if ((this.GetLocationListOperationCompleted == null)) {
                this.GetLocationListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLocationListOperationCompleted);
            }
            this.InvokeAsync("GetLocationList", new object[] {
                        Language,
                        Arrlocation}, this.GetLocationListOperationCompleted, userState);
        }
        
        private void OnGetLocationListOperationCompleted(object arg) {
            if ((this.GetLocationListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLocationListCompleted(this, new GetLocationListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetInstructors", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetInstructors(string SessionID, ref TRRInstructor[] ArrInstructor) {
            object[] results = this.Invoke("GetInstructors", new object[] {
                        SessionID,
                        ArrInstructor});
            ArrInstructor = ((TRRInstructor[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetInstructorsAsync(string SessionID, TRRInstructor[] ArrInstructor) {
            this.GetInstructorsAsync(SessionID, ArrInstructor, null);
        }
        
        /// <remarks/>
        public void GetInstructorsAsync(string SessionID, TRRInstructor[] ArrInstructor, object userState) {
            if ((this.GetInstructorsOperationCompleted == null)) {
                this.GetInstructorsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetInstructorsOperationCompleted);
            }
            this.InvokeAsync("GetInstructors", new object[] {
                        SessionID,
                        ArrInstructor}, this.GetInstructorsOperationCompleted, userState);
        }
        
        private void OnGetInstructorsOperationCompleted(object arg) {
            if ((this.GetInstructorsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetInstructorsCompleted(this, new GetInstructorsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#CustomerLogin", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool CustomerLogin(string UserName, string Password, ref string SessionID, ref string Disqualified) {
            object[] results = this.Invoke("CustomerLogin", new object[] {
                        UserName,
                        Password,
                        SessionID,
                        Disqualified});
            SessionID = ((string)(results[1]));
            Disqualified = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CustomerLoginAsync(string UserName, string Password, string SessionID, string Disqualified) {
            this.CustomerLoginAsync(UserName, Password, SessionID, Disqualified, null);
        }
        
        /// <remarks/>
        public void CustomerLoginAsync(string UserName, string Password, string SessionID, string Disqualified, object userState) {
            if ((this.CustomerLoginOperationCompleted == null)) {
                this.CustomerLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCustomerLoginOperationCompleted);
            }
            this.InvokeAsync("CustomerLogin", new object[] {
                        UserName,
                        Password,
                        SessionID,
                        Disqualified}, this.CustomerLoginOperationCompleted, userState);
        }
        
        private void OnCustomerLoginOperationCompleted(object arg) {
            if ((this.CustomerLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CustomerLoginCompleted(this, new CustomerLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetCustomerInfo", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetCustomerInfo(string SessionID, ref string Customercode, ref string Name, ref string Mobile, ref string Email) {
            object[] results = this.Invoke("GetCustomerInfo", new object[] {
                        SessionID,
                        Customercode,
                        Name,
                        Mobile,
                        Email});
            Customercode = ((string)(results[1]));
            Name = ((string)(results[2]));
            Mobile = ((string)(results[3]));
            Email = ((string)(results[4]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerInfoAsync(string SessionID, string Customercode, string Name, string Mobile, string Email) {
            this.GetCustomerInfoAsync(SessionID, Customercode, Name, Mobile, Email, null);
        }
        
        /// <remarks/>
        public void GetCustomerInfoAsync(string SessionID, string Customercode, string Name, string Mobile, string Email, object userState) {
            if ((this.GetCustomerInfoOperationCompleted == null)) {
                this.GetCustomerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerInfoOperationCompleted);
            }
            this.InvokeAsync("GetCustomerInfo", new object[] {
                        SessionID,
                        Customercode,
                        Name,
                        Mobile,
                        Email}, this.GetCustomerInfoOperationCompleted, userState);
        }
        
        private void OnGetCustomerInfoOperationCompleted(object arg) {
            if ((this.GetCustomerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerInfoCompleted(this, new GetCustomerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetCustomerRights", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetCustomerRights(string SessionID, ref string Contract, ref System.DateTime expireDate, ref TRRObjectCard[] ArrObjectCard) {
            object[] results = this.Invoke("GetCustomerRights", new object[] {
                        SessionID,
                        Contract,
                        expireDate,
                        ArrObjectCard});
            Contract = ((string)(results[1]));
            expireDate = ((System.DateTime)(results[2]));
            ArrObjectCard = ((TRRObjectCard[])(results[3]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerRightsAsync(string SessionID, string Contract, System.DateTime expireDate, TRRObjectCard[] ArrObjectCard) {
            this.GetCustomerRightsAsync(SessionID, Contract, expireDate, ArrObjectCard, null);
        }
        
        /// <remarks/>
        public void GetCustomerRightsAsync(string SessionID, string Contract, System.DateTime expireDate, TRRObjectCard[] ArrObjectCard, object userState) {
            if ((this.GetCustomerRightsOperationCompleted == null)) {
                this.GetCustomerRightsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerRightsOperationCompleted);
            }
            this.InvokeAsync("GetCustomerRights", new object[] {
                        SessionID,
                        Contract,
                        expireDate,
                        ArrObjectCard}, this.GetCustomerRightsOperationCompleted, userState);
        }
        
        private void OnGetCustomerRightsOperationCompleted(object arg) {
            if ((this.GetCustomerRightsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerRightsCompleted(this, new GetCustomerRightsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetObjectClassList", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetObjectClassList(string ObjectType, int Language, ref TRRObjectCLass[] ArrObjectClass) {
            object[] results = this.Invoke("GetObjectClassList", new object[] {
                        ObjectType,
                        Language,
                        ArrObjectClass});
            ArrObjectClass = ((TRRObjectCLass[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetObjectClassListAsync(string ObjectType, int Language, TRRObjectCLass[] ArrObjectClass) {
            this.GetObjectClassListAsync(ObjectType, Language, ArrObjectClass, null);
        }
        
        /// <remarks/>
        public void GetObjectClassListAsync(string ObjectType, int Language, TRRObjectCLass[] ArrObjectClass, object userState) {
            if ((this.GetObjectClassListOperationCompleted == null)) {
                this.GetObjectClassListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetObjectClassListOperationCompleted);
            }
            this.InvokeAsync("GetObjectClassList", new object[] {
                        ObjectType,
                        Language,
                        ArrObjectClass}, this.GetObjectClassListOperationCompleted, userState);
        }
        
        private void OnGetObjectClassListOperationCompleted(object arg) {
            if ((this.GetObjectClassListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetObjectClassListCompleted(this, new GetObjectClassListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetCustomerClassCode", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetCustomerClassCode(string SessionID, ref string CLassCode, ref int StatusCode) {
            object[] results = this.Invoke("GetCustomerClassCode", new object[] {
                        SessionID,
                        CLassCode,
                        StatusCode});
            CLassCode = ((string)(results[1]));
            StatusCode = ((int)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerClassCodeAsync(string SessionID, string CLassCode, int StatusCode) {
            this.GetCustomerClassCodeAsync(SessionID, CLassCode, StatusCode, null);
        }
        
        /// <remarks/>
        public void GetCustomerClassCodeAsync(string SessionID, string CLassCode, int StatusCode, object userState) {
            if ((this.GetCustomerClassCodeOperationCompleted == null)) {
                this.GetCustomerClassCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerClassCodeOperationCompleted);
            }
            this.InvokeAsync("GetCustomerClassCode", new object[] {
                        SessionID,
                        CLassCode,
                        StatusCode}, this.GetCustomerClassCodeOperationCompleted, userState);
        }
        
        private void OnGetCustomerClassCodeOperationCompleted(object arg) {
            if ((this.GetCustomerClassCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerClassCodeCompleted(this, new GetCustomerClassCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetCustomerReservations", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetCustomerReservations(string SessionID, ref TRRCustomerReservation[] ArrCustomerReservation) {
            object[] results = this.Invoke("GetCustomerReservations", new object[] {
                        SessionID,
                        ArrCustomerReservation});
            ArrCustomerReservation = ((TRRCustomerReservation[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerReservationsAsync(string SessionID, TRRCustomerReservation[] ArrCustomerReservation) {
            this.GetCustomerReservationsAsync(SessionID, ArrCustomerReservation, null);
        }
        
        /// <remarks/>
        public void GetCustomerReservationsAsync(string SessionID, TRRCustomerReservation[] ArrCustomerReservation, object userState) {
            if ((this.GetCustomerReservationsOperationCompleted == null)) {
                this.GetCustomerReservationsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerReservationsOperationCompleted);
            }
            this.InvokeAsync("GetCustomerReservations", new object[] {
                        SessionID,
                        ArrCustomerReservation}, this.GetCustomerReservationsOperationCompleted, userState);
        }
        
        private void OnGetCustomerReservationsOperationCompleted(object arg) {
            if ((this.GetCustomerReservationsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerReservationsCompleted(this, new GetCustomerReservationsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#CancelReservation", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool CancelReservation(string SessionID, string Location, int CLassID, int ReservationID, ref int ErrorStatus) {
            object[] results = this.Invoke("CancelReservation", new object[] {
                        SessionID,
                        Location,
                        CLassID,
                        ReservationID,
                        ErrorStatus});
            ErrorStatus = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelReservationAsync(string SessionID, string Location, int CLassID, int ReservationID, int ErrorStatus) {
            this.CancelReservationAsync(SessionID, Location, CLassID, ReservationID, ErrorStatus, null);
        }
        
        /// <remarks/>
        public void CancelReservationAsync(string SessionID, string Location, int CLassID, int ReservationID, int ErrorStatus, object userState) {
            if ((this.CancelReservationOperationCompleted == null)) {
                this.CancelReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelReservationOperationCompleted);
            }
            this.InvokeAsync("CancelReservation", new object[] {
                        SessionID,
                        Location,
                        CLassID,
                        ReservationID,
                        ErrorStatus}, this.CancelReservationOperationCompleted, userState);
        }
        
        private void OnCancelReservationOperationCompleted(object arg) {
            if ((this.CancelReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelReservationCompleted(this, new CancelReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#MakeReservation", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool MakeReservation(string SessionID, string Location, int CLassID, ref int ReservationID, ref int ErrorStatus) {
            object[] results = this.Invoke("MakeReservation", new object[] {
                        SessionID,
                        Location,
                        CLassID,
                        ReservationID,
                        ErrorStatus});
            ReservationID = ((int)(results[1]));
            ErrorStatus = ((int)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MakeReservationAsync(string SessionID, string Location, int CLassID, int ReservationID, int ErrorStatus) {
            this.MakeReservationAsync(SessionID, Location, CLassID, ReservationID, ErrorStatus, null);
        }
        
        /// <remarks/>
        public void MakeReservationAsync(string SessionID, string Location, int CLassID, int ReservationID, int ErrorStatus, object userState) {
            if ((this.MakeReservationOperationCompleted == null)) {
                this.MakeReservationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakeReservationOperationCompleted);
            }
            this.InvokeAsync("MakeReservation", new object[] {
                        SessionID,
                        Location,
                        CLassID,
                        ReservationID,
                        ErrorStatus}, this.MakeReservationOperationCompleted, userState);
        }
        
        private void OnMakeReservationOperationCompleted(object arg) {
            if ((this.MakeReservationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakeReservationCompleted(this, new MakeReservationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#MakeRsvToQueue", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool MakeRsvToQueue(string SessionID, string Location, int CLassID, ref int ErrorStatus) {
            object[] results = this.Invoke("MakeRsvToQueue", new object[] {
                        SessionID,
                        Location,
                        CLassID,
                        ErrorStatus});
            ErrorStatus = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void MakeRsvToQueueAsync(string SessionID, string Location, int CLassID, int ErrorStatus) {
            this.MakeRsvToQueueAsync(SessionID, Location, CLassID, ErrorStatus, null);
        }
        
        /// <remarks/>
        public void MakeRsvToQueueAsync(string SessionID, string Location, int CLassID, int ErrorStatus, object userState) {
            if ((this.MakeRsvToQueueOperationCompleted == null)) {
                this.MakeRsvToQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMakeRsvToQueueOperationCompleted);
            }
            this.InvokeAsync("MakeRsvToQueue", new object[] {
                        SessionID,
                        Location,
                        CLassID,
                        ErrorStatus}, this.MakeRsvToQueueOperationCompleted, userState);
        }
        
        private void OnMakeRsvToQueueOperationCompleted(object arg) {
            if ((this.MakeRsvToQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MakeRsvToQueueCompleted(this, new MakeRsvToQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#CancelQueue", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool CancelQueue(string SessionID, string Location, int CLassID, ref int ErrorStatus) {
            object[] results = this.Invoke("CancelQueue", new object[] {
                        SessionID,
                        Location,
                        CLassID,
                        ErrorStatus});
            ErrorStatus = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void CancelQueueAsync(string SessionID, string Location, int CLassID, int ErrorStatus) {
            this.CancelQueueAsync(SessionID, Location, CLassID, ErrorStatus, null);
        }
        
        /// <remarks/>
        public void CancelQueueAsync(string SessionID, string Location, int CLassID, int ErrorStatus, object userState) {
            if ((this.CancelQueueOperationCompleted == null)) {
                this.CancelQueueOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelQueueOperationCompleted);
            }
            this.InvokeAsync("CancelQueue", new object[] {
                        SessionID,
                        Location,
                        CLassID,
                        ErrorStatus}, this.CancelQueueOperationCompleted, userState);
        }
        
        private void OnCancelQueueOperationCompleted(object arg) {
            if ((this.CancelQueueCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelQueueCompleted(this, new CancelQueueCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetClasses", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetClasses(string SessionID, TLocationCode[] ArrLocationCode, TObjectClassCode[] ArrObjClassCode, TInstructorCode[] ArrInstructorCode, System.DateTime FirstDate, System.DateTime LastDate, ref TRRClass[] ArrClass) {
            object[] results = this.Invoke("GetClasses", new object[] {
                        SessionID,
                        ArrLocationCode,
                        ArrObjClassCode,
                        ArrInstructorCode,
                        FirstDate,
                        LastDate,
                        ArrClass});
            ArrClass = ((TRRClass[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetClassesAsync(string SessionID, TLocationCode[] ArrLocationCode, TObjectClassCode[] ArrObjClassCode, TInstructorCode[] ArrInstructorCode, System.DateTime FirstDate, System.DateTime LastDate, TRRClass[] ArrClass) {
            this.GetClassesAsync(SessionID, ArrLocationCode, ArrObjClassCode, ArrInstructorCode, FirstDate, LastDate, ArrClass, null);
        }
        
        /// <remarks/>
        public void GetClassesAsync(string SessionID, TLocationCode[] ArrLocationCode, TObjectClassCode[] ArrObjClassCode, TInstructorCode[] ArrInstructorCode, System.DateTime FirstDate, System.DateTime LastDate, TRRClass[] ArrClass, object userState) {
            if ((this.GetClassesOperationCompleted == null)) {
                this.GetClassesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetClassesOperationCompleted);
            }
            this.InvokeAsync("GetClasses", new object[] {
                        SessionID,
                        ArrLocationCode,
                        ArrObjClassCode,
                        ArrInstructorCode,
                        FirstDate,
                        LastDate,
                        ArrClass}, this.GetClassesOperationCompleted, userState);
        }
        
        private void OnGetClassesOperationCompleted(object arg) {
            if ((this.GetClassesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetClassesCompleted(this, new GetClassesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetTimeZoneInfo", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetTimeZoneInfo(ref int Bias_minutes) {
            object[] results = this.Invoke("GetTimeZoneInfo", new object[] {
                        Bias_minutes});
            Bias_minutes = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetTimeZoneInfoAsync(int Bias_minutes) {
            this.GetTimeZoneInfoAsync(Bias_minutes, null);
        }
        
        /// <remarks/>
        public void GetTimeZoneInfoAsync(int Bias_minutes, object userState) {
            if ((this.GetTimeZoneInfoOperationCompleted == null)) {
                this.GetTimeZoneInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTimeZoneInfoOperationCompleted);
            }
            this.InvokeAsync("GetTimeZoneInfo", new object[] {
                        Bias_minutes}, this.GetTimeZoneInfoOperationCompleted, userState);
        }
        
        private void OnGetTimeZoneInfoOperationCompleted(object arg) {
            if ((this.GetTimeZoneInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTimeZoneInfoCompleted(this, new GetTimeZoneInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetLanguages", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetLanguages(ref TRRLanguage[] ArrLanguage) {
            object[] results = this.Invoke("GetLanguages", new object[] {
                        ArrLanguage});
            ArrLanguage = ((TRRLanguage[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetLanguagesAsync(TRRLanguage[] ArrLanguage) {
            this.GetLanguagesAsync(ArrLanguage, null);
        }
        
        /// <remarks/>
        public void GetLanguagesAsync(TRRLanguage[] ArrLanguage, object userState) {
            if ((this.GetLanguagesOperationCompleted == null)) {
                this.GetLanguagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLanguagesOperationCompleted);
            }
            this.InvokeAsync("GetLanguages", new object[] {
                        ArrLanguage}, this.GetLanguagesOperationCompleted, userState);
        }
        
        private void OnGetLanguagesOperationCompleted(object arg) {
            if ((this.GetLanguagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLanguagesCompleted(this, new GetLanguagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#GetWebText", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool GetWebText(string Code, int Language, ref string text) {
            object[] results = this.Invoke("GetWebText", new object[] {
                        Code,
                        Language,
                        text});
            text = ((string)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetWebTextAsync(string Code, int Language, string text) {
            this.GetWebTextAsync(Code, Language, text, null);
        }
        
        /// <remarks/>
        public void GetWebTextAsync(string Code, int Language, string text, object userState) {
            if ((this.GetWebTextOperationCompleted == null)) {
                this.GetWebTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetWebTextOperationCompleted);
            }
            this.InvokeAsync("GetWebText", new object[] {
                        Code,
                        Language,
                        text}, this.GetWebTextOperationCompleted, userState);
        }
        
        private void OnGetWebTextOperationCompleted(object arg) {
            if ((this.GetWebTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetWebTextCompleted(this, new GetWebTextCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext#Dummy", RequestNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext", ResponseNamespace="urn:Dlp2wsIntfRR_Ext-IDlp2wsRR_Ext")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public bool Dummy(TRRReservation d1, string foo) {
            object[] results = this.Invoke("Dummy", new object[] {
                        d1,
                        foo});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DummyAsync(TRRReservation d1, string foo) {
            this.DummyAsync(d1, foo, null);
        }
        
        /// <remarks/>
        public void DummyAsync(TRRReservation d1, string foo, object userState) {
            if ((this.DummyOperationCompleted == null)) {
                this.DummyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDummyOperationCompleted);
            }
            this.InvokeAsync("Dummy", new object[] {
                        d1,
                        foo}, this.DummyOperationCompleted, userState);
        }
        
        private void OnDummyOperationCompleted(object arg) {
            if ((this.DummyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DummyCompleted(this, new DummyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TRRObject {
        
        private string codeField;
        
        private string descriptionField;
        
        private string classCodeField;
        
        private string classDescriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ClassDescription {
            get {
                return this.classDescriptionField;
            }
            set {
                this.classDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TRRLanguage {
        
        private int language_numberField;
        
        private string languageField;
        
        /// <remarks/>
        public int language_number {
            get {
                return this.language_numberField;
            }
            set {
                this.language_numberField = value;
            }
        }
        
        /// <remarks/>
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TRRClass {
        
        private int classIDField;
        
        private string class_descriptionField;
        
        private string special_remarkField;
        
        private string locationField;
        
        private string obj_codeField;
        
        private System.DateTime start_timeField;
        
        private System.DateTime end_timeField;
        
        private string space_codeField;
        
        private string instructor1_nameField;
        
        private string instructor2_nameField;
        
        private string instructor1_codeField;
        
        private string instructor2_codeField;
        
        private string obj_class_codeField;
        
        private string obj_class_descField;
        
        private string allow_rsvField;
        
        private int max_rsv_qtyField;
        
        private int max_web_rsv_qtyField;
        
        private int reservation_qtyField;
        
        /// <remarks/>
        public int ClassID {
            get {
                return this.classIDField;
            }
            set {
                this.classIDField = value;
            }
        }
        
        /// <remarks/>
        public string Class_description {
            get {
                return this.class_descriptionField;
            }
            set {
                this.class_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Special_remark {
            get {
                return this.special_remarkField;
            }
            set {
                this.special_remarkField = value;
            }
        }
        
        /// <remarks/>
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string Obj_code {
            get {
                return this.obj_codeField;
            }
            set {
                this.obj_codeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Start_time {
            get {
                return this.start_timeField;
            }
            set {
                this.start_timeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime End_time {
            get {
                return this.end_timeField;
            }
            set {
                this.end_timeField = value;
            }
        }
        
        /// <remarks/>
        public string Space_code {
            get {
                return this.space_codeField;
            }
            set {
                this.space_codeField = value;
            }
        }
        
        /// <remarks/>
        public string Instructor1_name {
            get {
                return this.instructor1_nameField;
            }
            set {
                this.instructor1_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Instructor2_name {
            get {
                return this.instructor2_nameField;
            }
            set {
                this.instructor2_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Instructor1_code {
            get {
                return this.instructor1_codeField;
            }
            set {
                this.instructor1_codeField = value;
            }
        }
        
        /// <remarks/>
        public string Instructor2_code {
            get {
                return this.instructor2_codeField;
            }
            set {
                this.instructor2_codeField = value;
            }
        }
        
        /// <remarks/>
        public string Obj_class_code {
            get {
                return this.obj_class_codeField;
            }
            set {
                this.obj_class_codeField = value;
            }
        }
        
        /// <remarks/>
        public string Obj_class_desc {
            get {
                return this.obj_class_descField;
            }
            set {
                this.obj_class_descField = value;
            }
        }
        
        /// <remarks/>
        public string Allow_rsv {
            get {
                return this.allow_rsvField;
            }
            set {
                this.allow_rsvField = value;
            }
        }
        
        /// <remarks/>
        public int Max_rsv_qty {
            get {
                return this.max_rsv_qtyField;
            }
            set {
                this.max_rsv_qtyField = value;
            }
        }
        
        /// <remarks/>
        public int Max_web_rsv_qty {
            get {
                return this.max_web_rsv_qtyField;
            }
            set {
                this.max_web_rsv_qtyField = value;
            }
        }
        
        /// <remarks/>
        public int Reservation_qty {
            get {
                return this.reservation_qtyField;
            }
            set {
                this.reservation_qtyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TInstructorCode {
        
        private string codeField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TObjectClassCode {
        
        private string codeField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TRRCustomerReservation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TRRReservation {
        
        private int classIDField;
        
        private string obj_codeField;
        
        private System.DateTime start_timeField;
        
        private System.DateTime end_timeField;
        
        private string locationField;
        
        private string space_codeField;
        
        private string instructor_codeField;
        
        private string instructor_code2Field;
        
        private string instructor_nameField;
        
        private string instructor_name2Field;
        
        /// <remarks/>
        public int classID {
            get {
                return this.classIDField;
            }
            set {
                this.classIDField = value;
            }
        }
        
        /// <remarks/>
        public string obj_code {
            get {
                return this.obj_codeField;
            }
            set {
                this.obj_codeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime start_time {
            get {
                return this.start_timeField;
            }
            set {
                this.start_timeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime end_time {
            get {
                return this.end_timeField;
            }
            set {
                this.end_timeField = value;
            }
        }
        
        /// <remarks/>
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        public string space_code {
            get {
                return this.space_codeField;
            }
            set {
                this.space_codeField = value;
            }
        }
        
        /// <remarks/>
        public string instructor_code {
            get {
                return this.instructor_codeField;
            }
            set {
                this.instructor_codeField = value;
            }
        }
        
        /// <remarks/>
        public string instructor_code2 {
            get {
                return this.instructor_code2Field;
            }
            set {
                this.instructor_code2Field = value;
            }
        }
        
        /// <remarks/>
        public string instructor_name {
            get {
                return this.instructor_nameField;
            }
            set {
                this.instructor_nameField = value;
            }
        }
        
        /// <remarks/>
        public string instructor_name2 {
            get {
                return this.instructor_name2Field;
            }
            set {
                this.instructor_name2Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TRRCustomerReservation : TRRReservation {
        
        private int reservationIDField;
        
        private string is_cancelableField;
        
        private int queue_positionField;
        
        /// <remarks/>
        public int ReservationID {
            get {
                return this.reservationIDField;
            }
            set {
                this.reservationIDField = value;
            }
        }
        
        /// <remarks/>
        public string Is_cancelable {
            get {
                return this.is_cancelableField;
            }
            set {
                this.is_cancelableField = value;
            }
        }
        
        /// <remarks/>
        public int Queue_position {
            get {
                return this.queue_positionField;
            }
            set {
                this.queue_positionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TRRObjectCLass {
        
        private string classCodeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string ClassCode {
            get {
                return this.classCodeField;
            }
            set {
                this.classCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TRRObjectCard {
        
        private string descriptionField;
        
        private string cardTypeField;
        
        private string obj_codeField;
        
        private System.DateTime expire_dateField;
        
        private int item_countField;
        
        private double saldoField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string CardType {
            get {
                return this.cardTypeField;
            }
            set {
                this.cardTypeField = value;
            }
        }
        
        /// <remarks/>
        public string Obj_code {
            get {
                return this.obj_codeField;
            }
            set {
                this.obj_codeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Expire_date {
            get {
                return this.expire_dateField;
            }
            set {
                this.expire_dateField = value;
            }
        }
        
        /// <remarks/>
        public int Item_count {
            get {
                return this.item_countField;
            }
            set {
                this.item_countField = value;
            }
        }
        
        /// <remarks/>
        public double Saldo {
            get {
                return this.saldoField;
            }
            set {
                this.saldoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TRRInstructor {
        
        private string codeField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(TLocation))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TLocationCode {
        
        private string codeField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TLocation : TLocationCode {
        
        private string descriptionField;
        
        private double latitudeField;
        
        private double longitudeField;
        
        private string address_1Field;
        
        private string address_2Field;
        
        private string zipField;
        
        private string cityField;
        
        private string telephoneField;
        
        private string emailField;
        
        private string url_homepageField;
        
        private string memo_textField;
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public double Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        public double Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <remarks/>
        public string Address_1 {
            get {
                return this.address_1Field;
            }
            set {
                this.address_1Field = value;
            }
        }
        
        /// <remarks/>
        public string Address_2 {
            get {
                return this.address_2Field;
            }
            set {
                this.address_2Field = value;
            }
        }
        
        /// <remarks/>
        public string zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string telephone {
            get {
                return this.telephoneField;
            }
            set {
                this.telephoneField = value;
            }
        }
        
        /// <remarks/>
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string url_homepage {
            get {
                return this.url_homepageField;
            }
            set {
                this.url_homepageField = value;
            }
        }
        
        /// <remarks/>
        public string memo_text {
            get {
                return this.memo_textField;
            }
            set {
                this.memo_textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:Dlp2wsClassesRR")]
    public partial class TRRSpace {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetObjectListCompletedEventHandler(object sender, GetObjectListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetObjectListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetObjectListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TRRObject[] ArrObject {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRRObject[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetSpaceListCompletedEventHandler(object sender, GetSpaceListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSpaceListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSpaceListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TRRSpace[] ArrSpace {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRRSpace[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLocationListCompletedEventHandler(object sender, GetLocationListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLocationListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLocationListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TLocation[] Arrlocation {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TLocation[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetInstructorsCompletedEventHandler(object sender, GetInstructorsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetInstructorsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetInstructorsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TRRInstructor[] ArrInstructor {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRRInstructor[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CustomerLoginCompletedEventHandler(object sender, CustomerLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CustomerLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CustomerLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string SessionID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Disqualified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCustomerInfoCompletedEventHandler(object sender, GetCustomerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Customercode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCustomerRightsCompletedEventHandler(object sender, GetCustomerRightsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerRightsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerRightsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string Contract {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public System.DateTime expireDate {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public TRRObjectCard[] ArrObjectCard {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRRObjectCard[])(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetObjectClassListCompletedEventHandler(object sender, GetObjectClassListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetObjectClassListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetObjectClassListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TRRObjectCLass[] ArrObjectClass {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRRObjectCLass[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCustomerClassCodeCompletedEventHandler(object sender, GetCustomerClassCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerClassCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerClassCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string CLassCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int StatusCode {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCustomerReservationsCompletedEventHandler(object sender, GetCustomerReservationsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerReservationsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerReservationsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TRRCustomerReservation[] ArrCustomerReservation {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRRCustomerReservation[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CancelReservationCompletedEventHandler(object sender, CancelReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int ErrorStatus {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MakeReservationCompletedEventHandler(object sender, MakeReservationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakeReservationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakeReservationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int ReservationID {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int ErrorStatus {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void MakeRsvToQueueCompletedEventHandler(object sender, MakeRsvToQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MakeRsvToQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MakeRsvToQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int ErrorStatus {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CancelQueueCompletedEventHandler(object sender, CancelQueueCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelQueueCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelQueueCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int ErrorStatus {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetClassesCompletedEventHandler(object sender, GetClassesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetClassesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetClassesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TRRClass[] ArrClass {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRRClass[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetTimeZoneInfoCompletedEventHandler(object sender, GetTimeZoneInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTimeZoneInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTimeZoneInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int Bias_minutes {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLanguagesCompletedEventHandler(object sender, GetLanguagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLanguagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLanguagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public TRRLanguage[] ArrLanguage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TRRLanguage[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetWebTextCompletedEventHandler(object sender, GetWebTextCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetWebTextCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetWebTextCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string text {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void DummyCompletedEventHandler(object sender, DummyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DummyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DummyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591