//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]

    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DatabaseEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DatabaseEntities object using the connection string found in the 'DatabaseEntities' section of the application configuration file.
        /// </summary>
        public DatabaseEntities() : base("name=DatabaseEntities", "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(string connectionString) : base(connectionString, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DatabaseEntities object.
        /// </summary>
        public DatabaseEntities(EntityConnection connection) : base(connection, "DatabaseEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<FacilityData> FacilityDatas
        {
            get
            {
                if ((_FacilityDatas == null))
                {
                    _FacilityDatas = base.CreateObjectSet<FacilityData>("FacilityDatas");
                }
                return _FacilityDatas;
            }
        }
        private ObjectSet<FacilityData> _FacilityDatas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the FacilityDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToFacilityDatas(FacilityData facilityData)
        {
            base.AddObject("FacilityDatas", facilityData);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DatabaseModel", Name="FacilityData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class FacilityData : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new FacilityData object.
        /// </summary>
        /// <param name="localId">Initial value of the LocalId property.</param>
        public static FacilityData CreateFacilityData(global::System.Guid localId)
        {
            FacilityData facilityData = new FacilityData();
            facilityData.LocalId = localId;
            return facilityData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid LocalId
        {
            get
            {
                return _LocalId;
            }
            set
            {
                if (_LocalId != value)
                {
                    OnLocalIdChanging(value);
                    ReportPropertyChanging("LocalId");
                    _LocalId = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LocalId");
                    OnLocalIdChanged();
                }
            }
        }
        private global::System.Guid _LocalId;
        partial void OnLocalIdChanging(global::System.Guid value);
        partial void OnLocalIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Id
        {
            get
            {
                return _Id;
            }
            set
            {
                OnIdChanging(value);
                ReportPropertyChanging("Id");
                _Id = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Id");
                OnIdChanged();
            }
        }
        private global::System.String _Id;
        partial void OnIdChanging(global::System.String value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Id2
        {
            get
            {
                return _Id2;
            }
            set
            {
                OnId2Changing(value);
                ReportPropertyChanging("Id2");
                _Id2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Id2");
                OnId2Changed();
            }
        }
        private global::System.String _Id2;
        partial void OnId2Changing(global::System.String value);
        partial void OnId2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HtmlInfo
        {
            get
            {
                return _HtmlInfo;
            }
            set
            {
                OnHtmlInfoChanging(value);
                ReportPropertyChanging("HtmlInfo");
                _HtmlInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HtmlInfo");
                OnHtmlInfoChanged();
            }
        }
        private global::System.String _HtmlInfo;
        partial void OnHtmlInfoChanging(global::System.String value);
        partial void OnHtmlInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Longitude
        {
            get
            {
                return _Longitude;
            }
            set
            {
                OnLongitudeChanging(value);
                ReportPropertyChanging("Longitude");
                _Longitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Longitude");
                OnLongitudeChanged();
            }
        }
        private global::System.String _Longitude;
        partial void OnLongitudeChanging(global::System.String value);
        partial void OnLongitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Latitude
        {
            get
            {
                return _Latitude;
            }
            set
            {
                OnLatitudeChanging(value);
                ReportPropertyChanging("Latitude");
                _Latitude = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Latitude");
                OnLatitudeChanged();
            }
        }
        private global::System.String _Latitude;
        partial void OnLatitudeChanging(global::System.String value);
        partial void OnLatitudeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> Visible
        {
            get
            {
                return _Visible;
            }
            set
            {
                OnVisibleChanging(value);
                ReportPropertyChanging("Visible");
                _Visible = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Visible");
                OnVisibleChanged();
            }
        }
        private Nullable<global::System.Boolean> _Visible;
        partial void OnVisibleChanging(Nullable<global::System.Boolean> value);
        partial void OnVisibleChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> VisibleGuid
        {
            get
            {
                return _VisibleGuid;
            }
            set
            {
                OnVisibleGuidChanging(value);
                ReportPropertyChanging("VisibleGuid");
                _VisibleGuid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("VisibleGuid");
                OnVisibleGuidChanged();
            }
        }
        private Nullable<global::System.Guid> _VisibleGuid;
        partial void OnVisibleGuidChanging(Nullable<global::System.Guid> value);
        partial void OnVisibleGuidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceUrl
        {
            get
            {
                return _ServiceUrl;
            }
            set
            {
                OnServiceUrlChanging(value);
                ReportPropertyChanging("ServiceUrl");
                _ServiceUrl = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceUrl");
                OnServiceUrlChanged();
            }
        }
        private global::System.String _ServiceUrl;
        partial void OnServiceUrlChanging(global::System.String value);
        partial void OnServiceUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceLicense
        {
            get
            {
                return _ServiceLicense;
            }
            set
            {
                OnServiceLicenseChanging(value);
                ReportPropertyChanging("ServiceLicense");
                _ServiceLicense = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceLicense");
                OnServiceLicenseChanged();
            }
        }
        private global::System.String _ServiceLicense;
        partial void OnServiceLicenseChanging(global::System.String value);
        partial void OnServiceLicenseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceRevision
        {
            get
            {
                return _ServiceRevision;
            }
            set
            {
                OnServiceRevisionChanging(value);
                ReportPropertyChanging("ServiceRevision");
                _ServiceRevision = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceRevision");
                OnServiceRevisionChanged();
            }
        }
        private global::System.String _ServiceRevision;
        partial void OnServiceRevisionChanging(global::System.String value);
        partial void OnServiceRevisionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceContextId
        {
            get
            {
                return _ServiceContextId;
            }
            set
            {
                OnServiceContextIdChanging(value);
                ReportPropertyChanging("ServiceContextId");
                _ServiceContextId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceContextId");
                OnServiceContextIdChanged();
            }
        }
        private global::System.String _ServiceContextId;
        partial void OnServiceContextIdChanging(global::System.String value);
        partial void OnServiceContextIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> ScheduleLoginNeeded
        {
            get
            {
                return _ScheduleLoginNeeded;
            }
            set
            {
                OnScheduleLoginNeededChanging(value);
                ReportPropertyChanging("ScheduleLoginNeeded");
                _ScheduleLoginNeeded = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScheduleLoginNeeded");
                OnScheduleLoginNeededChanged();
            }
        }
        private Nullable<global::System.Boolean> _ScheduleLoginNeeded;
        partial void OnScheduleLoginNeededChanging(Nullable<global::System.Boolean> value);
        partial void OnScheduleLoginNeededChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LoginId
        {
            get
            {
                return _LoginId;
            }
            set
            {
                OnLoginIdChanging(value);
                ReportPropertyChanging("LoginId");
                _LoginId = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LoginId");
                OnLoginIdChanged();
            }
        }
        private global::System.String _LoginId;
        partial void OnLoginIdChanging(global::System.String value);
        partial void OnLoginIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ServiceType
        {
            get
            {
                return _ServiceType;
            }
            set
            {
                OnServiceTypeChanging(value);
                ReportPropertyChanging("ServiceType");
                _ServiceType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ServiceType");
                OnServiceTypeChanged();
            }
        }
        private global::System.String _ServiceType;
        partial void OnServiceTypeChanging(global::System.String value);
        partial void OnServiceTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Languages
        {
            get
            {
                return _Languages;
            }
            set
            {
                OnLanguagesChanging(value);
                ReportPropertyChanging("Languages");
                _Languages = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Languages");
                OnLanguagesChanged();
            }
        }
        private global::System.String _Languages;
        partial void OnLanguagesChanging(global::System.String value);
        partial void OnLanguagesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Homepage
        {
            get
            {
                return _Homepage;
            }
            set
            {
                OnHomepageChanging(value);
                ReportPropertyChanging("Homepage");
                _Homepage = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Homepage");
                OnHomepageChanged();
            }
        }
        private global::System.String _Homepage;
        partial void OnHomepageChanging(global::System.String value);
        partial void OnHomepageChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Twitter
        {
            get
            {
                return _Twitter;
            }
            set
            {
                OnTwitterChanging(value);
                ReportPropertyChanging("Twitter");
                _Twitter = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Twitter");
                OnTwitterChanged();
            }
        }
        private global::System.String _Twitter;
        partial void OnTwitterChanging(global::System.String value);
        partial void OnTwitterChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Facebook
        {
            get
            {
                return _Facebook;
            }
            set
            {
                OnFacebookChanging(value);
                ReportPropertyChanging("Facebook");
                _Facebook = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Facebook");
                OnFacebookChanged();
            }
        }
        private global::System.String _Facebook;
        partial void OnFacebookChanging(global::System.String value);
        partial void OnFacebookChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Zipcode
        {
            get
            {
                return _Zipcode;
            }
            set
            {
                OnZipcodeChanging(value);
                ReportPropertyChanging("Zipcode");
                _Zipcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Zipcode");
                OnZipcodeChanged();
            }
        }
        private global::System.String _Zipcode;
        partial void OnZipcodeChanging(global::System.String value);
        partial void OnZipcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String News
        {
            get
            {
                return _News;
            }
            set
            {
                OnNewsChanging(value);
                ReportPropertyChanging("News");
                _News = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("News");
                OnNewsChanged();
            }
        }
        private global::System.String _News;
        partial void OnNewsChanging(global::System.String value);
        partial void OnNewsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Offers
        {
            get
            {
                return _Offers;
            }
            set
            {
                OnOffersChanging(value);
                ReportPropertyChanging("Offers");
                _Offers = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Offers");
                OnOffersChanged();
            }
        }
        private global::System.String _Offers;
        partial void OnOffersChanging(global::System.String value);
        partial void OnOffersChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String About
        {
            get
            {
                return _About;
            }
            set
            {
                OnAboutChanging(value);
                ReportPropertyChanging("About");
                _About = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("About");
                OnAboutChanged();
            }
        }
        private global::System.String _About;
        partial void OnAboutChanging(global::System.String value);
        partial void OnAboutChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UsernameLabel
        {
            get
            {
                return _UsernameLabel;
            }
            set
            {
                OnUsernameLabelChanging(value);
                ReportPropertyChanging("UsernameLabel");
                _UsernameLabel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UsernameLabel");
                OnUsernameLabelChanged();
            }
        }
        private global::System.String _UsernameLabel;
        partial void OnUsernameLabelChanging(global::System.String value);
        partial void OnUsernameLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordLabel
        {
            get
            {
                return _PasswordLabel;
            }
            set
            {
                OnPasswordLabelChanging(value);
                ReportPropertyChanging("PasswordLabel");
                _PasswordLabel = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PasswordLabel");
                OnPasswordLabelChanged();
            }
        }
        private global::System.String _PasswordLabel;
        partial void OnPasswordLabelChanging(global::System.String value);
        partial void OnPasswordLabelChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ScheduleLength
        {
            get
            {
                return _ScheduleLength;
            }
            set
            {
                OnScheduleLengthChanging(value);
                ReportPropertyChanging("ScheduleLength");
                _ScheduleLength = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ScheduleLength");
                OnScheduleLengthChanged();
            }
        }
        private Nullable<global::System.Int32> _ScheduleLength;
        partial void OnScheduleLengthChanging(Nullable<global::System.Int32> value);
        partial void OnScheduleLengthChanged();

        #endregion

    
    }

    #endregion
