//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.261.
// 
#pragma warning disable 1591

namespace FriskisSvettisLib.PastellMobileService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MobileServicesSoap", Namespace="http://tempuri.org/")]
    public partial class MobileServices : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback versionOperationCompleted;
        
        private System.Threading.SendOrPostCallback processOperationCompleted;
        
        private System.Threading.SendOrPostCallback processUnsafeOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback bookReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback debookReserveOperationCompleted;
        
        private System.Threading.SendOrPostCallback bookOperationCompleted;
        
        private System.Threading.SendOrPostCallback debookOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchbookingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchReserveBookingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchBOSOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchBOSPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchBOSGidOperationCompleted;
        
        private System.Threading.SendOrPostCallback fetchBOSGidPageOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MobileServices() {
            this.Url = global::FriskisSvettisLib.Properties.Settings.Default.FriskisSvettisLib_PastellMobileService_MobileServices;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event versionCompletedEventHandler versionCompleted;
        
        /// <remarks/>
        public event processCompletedEventHandler processCompleted;
        
        /// <remarks/>
        public event processUnsafeCompletedEventHandler processUnsafeCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event bookReserveCompletedEventHandler bookReserveCompleted;
        
        /// <remarks/>
        public event debookReserveCompletedEventHandler debookReserveCompleted;
        
        /// <remarks/>
        public event bookCompletedEventHandler bookCompleted;
        
        /// <remarks/>
        public event debookCompletedEventHandler debookCompleted;
        
        /// <remarks/>
        public event fetchbookingsCompletedEventHandler fetchbookingsCompleted;
        
        /// <remarks/>
        public event fetchReserveBookingsCompletedEventHandler fetchReserveBookingsCompleted;
        
        /// <remarks/>
        public event fetchBOSCompletedEventHandler fetchBOSCompleted;
        
        /// <remarks/>
        public event fetchBOSPageCompletedEventHandler fetchBOSPageCompleted;
        
        /// <remarks/>
        public event fetchBOSGidCompletedEventHandler fetchBOSGidCompleted;
        
        /// <remarks/>
        public event fetchBOSGidPageCompletedEventHandler fetchBOSGidPageCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/version", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string version(string xml) {
            object[] results = this.Invoke("version", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void versionAsync(string xml) {
            this.versionAsync(xml, null);
        }
        
        /// <remarks/>
        public void versionAsync(string xml, object userState) {
            if ((this.versionOperationCompleted == null)) {
                this.versionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnversionOperationCompleted);
            }
            this.InvokeAsync("version", new object[] {
                        xml}, this.versionOperationCompleted, userState);
        }
        
        private void OnversionOperationCompleted(object arg) {
            if ((this.versionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.versionCompleted(this, new versionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/process", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string process(string xml) {
            object[] results = this.Invoke("process", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void processAsync(string xml) {
            this.processAsync(xml, null);
        }
        
        /// <remarks/>
        public void processAsync(string xml, object userState) {
            if ((this.processOperationCompleted == null)) {
                this.processOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessOperationCompleted);
            }
            this.InvokeAsync("process", new object[] {
                        xml}, this.processOperationCompleted, userState);
        }
        
        private void OnprocessOperationCompleted(object arg) {
            if ((this.processCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processCompleted(this, new processCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/processUnsafe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string processUnsafe(string xml) {
            object[] results = this.Invoke("processUnsafe", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void processUnsafeAsync(string xml) {
            this.processUnsafeAsync(xml, null);
        }
        
        /// <remarks/>
        public void processUnsafeAsync(string xml, object userState) {
            if ((this.processUnsafeOperationCompleted == null)) {
                this.processUnsafeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnprocessUnsafeOperationCompleted);
            }
            this.InvokeAsync("processUnsafe", new object[] {
                        xml}, this.processUnsafeOperationCompleted, userState);
        }
        
        private void OnprocessUnsafeOperationCompleted(object arg) {
            if ((this.processUnsafeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.processUnsafeCompleted(this, new processUnsafeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string login(string key, string globalunit, string username, string password, string revision) {
            object[] results = this.Invoke("login", new object[] {
                        key,
                        globalunit,
                        username,
                        password,
                        revision});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string key, string globalunit, string username, string password, string revision) {
            this.loginAsync(key, globalunit, username, password, revision, null);
        }
        
        /// <remarks/>
        public void loginAsync(string key, string globalunit, string username, string password, string revision, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        key,
                        globalunit,
                        username,
                        password,
                        revision}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/bookReserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string bookReserve(string key, string guid, string username, string password, string boid, string revision) {
            object[] results = this.Invoke("bookReserve", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        boid,
                        revision});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void bookReserveAsync(string key, string guid, string username, string password, string boid, string revision) {
            this.bookReserveAsync(key, guid, username, password, boid, revision, null);
        }
        
        /// <remarks/>
        public void bookReserveAsync(string key, string guid, string username, string password, string boid, string revision, object userState) {
            if ((this.bookReserveOperationCompleted == null)) {
                this.bookReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbookReserveOperationCompleted);
            }
            this.InvokeAsync("bookReserve", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        boid,
                        revision}, this.bookReserveOperationCompleted, userState);
        }
        
        private void OnbookReserveOperationCompleted(object arg) {
            if ((this.bookReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bookReserveCompleted(this, new bookReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/debookReserve", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string debookReserve(string key, string guid, string username, string password, string reservbid, string revision) {
            object[] results = this.Invoke("debookReserve", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        reservbid,
                        revision});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void debookReserveAsync(string key, string guid, string username, string password, string reservbid, string revision) {
            this.debookReserveAsync(key, guid, username, password, reservbid, revision, null);
        }
        
        /// <remarks/>
        public void debookReserveAsync(string key, string guid, string username, string password, string reservbid, string revision, object userState) {
            if ((this.debookReserveOperationCompleted == null)) {
                this.debookReserveOperationCompleted = new System.Threading.SendOrPostCallback(this.OndebookReserveOperationCompleted);
            }
            this.InvokeAsync("debookReserve", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        reservbid,
                        revision}, this.debookReserveOperationCompleted, userState);
        }
        
        private void OndebookReserveOperationCompleted(object arg) {
            if ((this.debookReserveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.debookReserveCompleted(this, new debookReserveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/book", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string book(string key, string guid, string username, string password, string boid, string revision) {
            object[] results = this.Invoke("book", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        boid,
                        revision});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void bookAsync(string key, string guid, string username, string password, string boid, string revision) {
            this.bookAsync(key, guid, username, password, boid, revision, null);
        }
        
        /// <remarks/>
        public void bookAsync(string key, string guid, string username, string password, string boid, string revision, object userState) {
            if ((this.bookOperationCompleted == null)) {
                this.bookOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbookOperationCompleted);
            }
            this.InvokeAsync("book", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        boid,
                        revision}, this.bookOperationCompleted, userState);
        }
        
        private void OnbookOperationCompleted(object arg) {
            if ((this.bookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bookCompleted(this, new bookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/debook", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string debook(string key, string guid, string username, string password, string bid, string revision) {
            object[] results = this.Invoke("debook", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        bid,
                        revision});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void debookAsync(string key, string guid, string username, string password, string bid, string revision) {
            this.debookAsync(key, guid, username, password, bid, revision, null);
        }
        
        /// <remarks/>
        public void debookAsync(string key, string guid, string username, string password, string bid, string revision, object userState) {
            if ((this.debookOperationCompleted == null)) {
                this.debookOperationCompleted = new System.Threading.SendOrPostCallback(this.OndebookOperationCompleted);
            }
            this.InvokeAsync("debook", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        bid,
                        revision}, this.debookOperationCompleted, userState);
        }
        
        private void OndebookOperationCompleted(object arg) {
            if ((this.debookCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.debookCompleted(this, new debookCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fetchbookings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string fetchbookings(string key, string guid, string username, string password, string date, string revision) {
            object[] results = this.Invoke("fetchbookings", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        date,
                        revision});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fetchbookingsAsync(string key, string guid, string username, string password, string date, string revision) {
            this.fetchbookingsAsync(key, guid, username, password, date, revision, null);
        }
        
        /// <remarks/>
        public void fetchbookingsAsync(string key, string guid, string username, string password, string date, string revision, object userState) {
            if ((this.fetchbookingsOperationCompleted == null)) {
                this.fetchbookingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchbookingsOperationCompleted);
            }
            this.InvokeAsync("fetchbookings", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        date,
                        revision}, this.fetchbookingsOperationCompleted, userState);
        }
        
        private void OnfetchbookingsOperationCompleted(object arg) {
            if ((this.fetchbookingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchbookingsCompleted(this, new fetchbookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fetchReserveBookings", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string fetchReserveBookings(string key, string guid, string username, string password, string date, string revision) {
            object[] results = this.Invoke("fetchReserveBookings", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        date,
                        revision});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fetchReserveBookingsAsync(string key, string guid, string username, string password, string date, string revision) {
            this.fetchReserveBookingsAsync(key, guid, username, password, date, revision, null);
        }
        
        /// <remarks/>
        public void fetchReserveBookingsAsync(string key, string guid, string username, string password, string date, string revision, object userState) {
            if ((this.fetchReserveBookingsOperationCompleted == null)) {
                this.fetchReserveBookingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchReserveBookingsOperationCompleted);
            }
            this.InvokeAsync("fetchReserveBookings", new object[] {
                        key,
                        guid,
                        username,
                        password,
                        date,
                        revision}, this.fetchReserveBookingsOperationCompleted, userState);
        }
        
        private void OnfetchReserveBookingsOperationCompleted(object arg) {
            if ((this.fetchReserveBookingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchReserveBookingsCompleted(this, new fetchReserveBookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fetchBOS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string fetchBOS(string guid, string selecteddate, string user, string password) {
            object[] results = this.Invoke("fetchBOS", new object[] {
                        guid,
                        selecteddate,
                        user,
                        password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fetchBOSAsync(string guid, string selecteddate, string user, string password) {
            this.fetchBOSAsync(guid, selecteddate, user, password, null);
        }
        
        /// <remarks/>
        public void fetchBOSAsync(string guid, string selecteddate, string user, string password, object userState) {
            if ((this.fetchBOSOperationCompleted == null)) {
                this.fetchBOSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchBOSOperationCompleted);
            }
            this.InvokeAsync("fetchBOS", new object[] {
                        guid,
                        selecteddate,
                        user,
                        password}, this.fetchBOSOperationCompleted, userState);
        }
        
        private void OnfetchBOSOperationCompleted(object arg) {
            if ((this.fetchBOSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchBOSCompleted(this, new fetchBOSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fetchBOSPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string fetchBOSPage(string guid, string date, string user, string password, int page) {
            object[] results = this.Invoke("fetchBOSPage", new object[] {
                        guid,
                        date,
                        user,
                        password,
                        page});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fetchBOSPageAsync(string guid, string date, string user, string password, int page) {
            this.fetchBOSPageAsync(guid, date, user, password, page, null);
        }
        
        /// <remarks/>
        public void fetchBOSPageAsync(string guid, string date, string user, string password, int page, object userState) {
            if ((this.fetchBOSPageOperationCompleted == null)) {
                this.fetchBOSPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchBOSPageOperationCompleted);
            }
            this.InvokeAsync("fetchBOSPage", new object[] {
                        guid,
                        date,
                        user,
                        password,
                        page}, this.fetchBOSPageOperationCompleted, userState);
        }
        
        private void OnfetchBOSPageOperationCompleted(object arg) {
            if ((this.fetchBOSPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchBOSPageCompleted(this, new fetchBOSPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fetchBOSGid", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string fetchBOSGid(string guid, string selecteddate, string user, string password, string globalunit) {
            object[] results = this.Invoke("fetchBOSGid", new object[] {
                        guid,
                        selecteddate,
                        user,
                        password,
                        globalunit});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fetchBOSGidAsync(string guid, string selecteddate, string user, string password, string globalunit) {
            this.fetchBOSGidAsync(guid, selecteddate, user, password, globalunit, null);
        }
        
        /// <remarks/>
        public void fetchBOSGidAsync(string guid, string selecteddate, string user, string password, string globalunit, object userState) {
            if ((this.fetchBOSGidOperationCompleted == null)) {
                this.fetchBOSGidOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchBOSGidOperationCompleted);
            }
            this.InvokeAsync("fetchBOSGid", new object[] {
                        guid,
                        selecteddate,
                        user,
                        password,
                        globalunit}, this.fetchBOSGidOperationCompleted, userState);
        }
        
        private void OnfetchBOSGidOperationCompleted(object arg) {
            if ((this.fetchBOSGidCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchBOSGidCompleted(this, new fetchBOSGidCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/fetchBOSGidPage", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string fetchBOSGidPage(string guid, string selecteddate, string user, string password, string globalunit, int page) {
            object[] results = this.Invoke("fetchBOSGidPage", new object[] {
                        guid,
                        selecteddate,
                        user,
                        password,
                        globalunit,
                        page});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void fetchBOSGidPageAsync(string guid, string selecteddate, string user, string password, string globalunit, int page) {
            this.fetchBOSGidPageAsync(guid, selecteddate, user, password, globalunit, page, null);
        }
        
        /// <remarks/>
        public void fetchBOSGidPageAsync(string guid, string selecteddate, string user, string password, string globalunit, int page, object userState) {
            if ((this.fetchBOSGidPageOperationCompleted == null)) {
                this.fetchBOSGidPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchBOSGidPageOperationCompleted);
            }
            this.InvokeAsync("fetchBOSGidPage", new object[] {
                        guid,
                        selecteddate,
                        user,
                        password,
                        globalunit,
                        page}, this.fetchBOSGidPageOperationCompleted, userState);
        }
        
        private void OnfetchBOSGidPageOperationCompleted(object arg) {
            if ((this.fetchBOSGidPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchBOSGidPageCompleted(this, new fetchBOSGidPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void versionCompletedEventHandler(object sender, versionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class versionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal versionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void processCompletedEventHandler(object sender, processCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void processUnsafeCompletedEventHandler(object sender, processUnsafeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class processUnsafeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal processUnsafeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void bookReserveCompletedEventHandler(object sender, bookReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bookReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bookReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void debookReserveCompletedEventHandler(object sender, debookReserveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class debookReserveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal debookReserveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void bookCompletedEventHandler(object sender, bookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void debookCompletedEventHandler(object sender, debookCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class debookCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal debookCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void fetchbookingsCompletedEventHandler(object sender, fetchbookingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchbookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchbookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void fetchReserveBookingsCompletedEventHandler(object sender, fetchReserveBookingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchReserveBookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchReserveBookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void fetchBOSCompletedEventHandler(object sender, fetchBOSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchBOSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchBOSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void fetchBOSPageCompletedEventHandler(object sender, fetchBOSPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchBOSPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchBOSPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void fetchBOSGidCompletedEventHandler(object sender, fetchBOSGidCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchBOSGidCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchBOSGidCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void fetchBOSGidPageCompletedEventHandler(object sender, fetchBOSGidPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchBOSGidPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal fetchBOSGidPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591