//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FriskisSvettisLib.PastellWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PastellWebService.MobileServicesSoap")]
    public interface MobileServicesSoap {
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/version", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.versionResponse version(FriskisSvettisLib.PastellWebService.versionRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/process", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.processResponse process(FriskisSvettisLib.PastellWebService.processRequest request);
        
        // CODEGEN: Generating message contract since element name xml from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/processUnsafe", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.processUnsafeResponse processUnsafe(FriskisSvettisLib.PastellWebService.processUnsafeRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.loginResponse login(FriskisSvettisLib.PastellWebService.loginRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/bookReserve", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.bookReserveResponse bookReserve(FriskisSvettisLib.PastellWebService.bookReserveRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/debookReserve", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.debookReserveResponse debookReserve(FriskisSvettisLib.PastellWebService.debookReserveRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/book", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.bookResponse book(FriskisSvettisLib.PastellWebService.bookRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/debook", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.debookResponse debook(FriskisSvettisLib.PastellWebService.debookRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fetchbookings", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.fetchbookingsResponse fetchbookings(FriskisSvettisLib.PastellWebService.fetchbookingsRequest request);
        
        // CODEGEN: Generating message contract since element name key from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fetchReserveBookings", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.fetchReserveBookingsResponse fetchReserveBookings(FriskisSvettisLib.PastellWebService.fetchReserveBookingsRequest request);
        
        // CODEGEN: Generating message contract since element name guid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fetchBOS", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.fetchBOSResponse fetchBOS(FriskisSvettisLib.PastellWebService.fetchBOSRequest request);
        
        // CODEGEN: Generating message contract since element name guid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fetchBOSPage", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.fetchBOSPageResponse fetchBOSPage(FriskisSvettisLib.PastellWebService.fetchBOSPageRequest request);
        
        // CODEGEN: Generating message contract since element name guid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fetchBOSGid", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.fetchBOSGidResponse fetchBOSGid(FriskisSvettisLib.PastellWebService.fetchBOSGidRequest request);
        
        // CODEGEN: Generating message contract since element name guid from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fetchBOSGidPage", ReplyAction="*")]
        FriskisSvettisLib.PastellWebService.fetchBOSGidPageResponse fetchBOSGidPage(FriskisSvettisLib.PastellWebService.fetchBOSGidPageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class versionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="version", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.versionRequestBody Body;
        
        public versionRequest() {
        }
        
        public versionRequest(FriskisSvettisLib.PastellWebService.versionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class versionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public versionRequestBody() {
        }
        
        public versionRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class versionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="versionResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.versionResponseBody Body;
        
        public versionResponse() {
        }
        
        public versionResponse(FriskisSvettisLib.PastellWebService.versionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class versionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string versionResult;
        
        public versionResponseBody() {
        }
        
        public versionResponseBody(string versionResult) {
            this.versionResult = versionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="process", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.processRequestBody Body;
        
        public processRequest() {
        }
        
        public processRequest(FriskisSvettisLib.PastellWebService.processRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class processRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public processRequestBody() {
        }
        
        public processRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.processResponseBody Body;
        
        public processResponse() {
        }
        
        public processResponse(FriskisSvettisLib.PastellWebService.processResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class processResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string processResult;
        
        public processResponseBody() {
        }
        
        public processResponseBody(string processResult) {
            this.processResult = processResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processUnsafeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processUnsafe", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.processUnsafeRequestBody Body;
        
        public processUnsafeRequest() {
        }
        
        public processUnsafeRequest(FriskisSvettisLib.PastellWebService.processUnsafeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class processUnsafeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xml;
        
        public processUnsafeRequestBody() {
        }
        
        public processUnsafeRequestBody(string xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class processUnsafeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="processUnsafeResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.processUnsafeResponseBody Body;
        
        public processUnsafeResponse() {
        }
        
        public processUnsafeResponse(FriskisSvettisLib.PastellWebService.processUnsafeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class processUnsafeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string processUnsafeResult;
        
        public processUnsafeResponseBody() {
        }
        
        public processUnsafeResponseBody(string processUnsafeResult) {
            this.processUnsafeResult = processUnsafeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(FriskisSvettisLib.PastellWebService.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string globalunit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string revision;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string key, string globalunit, string username, string password, string revision) {
            this.key = key;
            this.globalunit = globalunit;
            this.username = username;
            this.password = password;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(FriskisSvettisLib.PastellWebService.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bookReserveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bookReserve", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.bookReserveRequestBody Body;
        
        public bookReserveRequest() {
        }
        
        public bookReserveRequest(FriskisSvettisLib.PastellWebService.bookReserveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bookReserveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string boid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string revision;
        
        public bookReserveRequestBody() {
        }
        
        public bookReserveRequestBody(string key, string guid, string username, string password, string boid, string revision) {
            this.key = key;
            this.guid = guid;
            this.username = username;
            this.password = password;
            this.boid = boid;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bookReserveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bookReserveResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.bookReserveResponseBody Body;
        
        public bookReserveResponse() {
        }
        
        public bookReserveResponse(FriskisSvettisLib.PastellWebService.bookReserveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bookReserveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookReserveResult;
        
        public bookReserveResponseBody() {
        }
        
        public bookReserveResponseBody(string bookReserveResult) {
            this.bookReserveResult = bookReserveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class debookReserveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="debookReserve", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.debookReserveRequestBody Body;
        
        public debookReserveRequest() {
        }
        
        public debookReserveRequest(FriskisSvettisLib.PastellWebService.debookReserveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class debookReserveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string reservbid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string revision;
        
        public debookReserveRequestBody() {
        }
        
        public debookReserveRequestBody(string key, string guid, string username, string password, string reservbid, string revision) {
            this.key = key;
            this.guid = guid;
            this.username = username;
            this.password = password;
            this.reservbid = reservbid;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class debookReserveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="debookReserveResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.debookReserveResponseBody Body;
        
        public debookReserveResponse() {
        }
        
        public debookReserveResponse(FriskisSvettisLib.PastellWebService.debookReserveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class debookReserveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string debookReserveResult;
        
        public debookReserveResponseBody() {
        }
        
        public debookReserveResponseBody(string debookReserveResult) {
            this.debookReserveResult = debookReserveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="book", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.bookRequestBody Body;
        
        public bookRequest() {
        }
        
        public bookRequest(FriskisSvettisLib.PastellWebService.bookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string boid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string revision;
        
        public bookRequestBody() {
        }
        
        public bookRequestBody(string key, string guid, string username, string password, string boid, string revision) {
            this.key = key;
            this.guid = guid;
            this.username = username;
            this.password = password;
            this.boid = boid;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class bookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="bookResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.bookResponseBody Body;
        
        public bookResponse() {
        }
        
        public bookResponse(FriskisSvettisLib.PastellWebService.bookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class bookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookResult;
        
        public bookResponseBody() {
        }
        
        public bookResponseBody(string bookResult) {
            this.bookResult = bookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class debookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="debook", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.debookRequestBody Body;
        
        public debookRequest() {
        }
        
        public debookRequest(FriskisSvettisLib.PastellWebService.debookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class debookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string bid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string revision;
        
        public debookRequestBody() {
        }
        
        public debookRequestBody(string key, string guid, string username, string password, string bid, string revision) {
            this.key = key;
            this.guid = guid;
            this.username = username;
            this.password = password;
            this.bid = bid;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class debookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="debookResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.debookResponseBody Body;
        
        public debookResponse() {
        }
        
        public debookResponse(FriskisSvettisLib.PastellWebService.debookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class debookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string debookResult;
        
        public debookResponseBody() {
        }
        
        public debookResponseBody(string debookResult) {
            this.debookResult = debookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchbookingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchbookings", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchbookingsRequestBody Body;
        
        public fetchbookingsRequest() {
        }
        
        public fetchbookingsRequest(FriskisSvettisLib.PastellWebService.fetchbookingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchbookingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string revision;
        
        public fetchbookingsRequestBody() {
        }
        
        public fetchbookingsRequestBody(string key, string guid, string username, string password, string date, string revision) {
            this.key = key;
            this.guid = guid;
            this.username = username;
            this.password = password;
            this.date = date;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchbookingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchbookingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchbookingsResponseBody Body;
        
        public fetchbookingsResponse() {
        }
        
        public fetchbookingsResponse(FriskisSvettisLib.PastellWebService.fetchbookingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchbookingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fetchbookingsResult;
        
        public fetchbookingsResponseBody() {
        }
        
        public fetchbookingsResponseBody(string fetchbookingsResult) {
            this.fetchbookingsResult = fetchbookingsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchReserveBookingsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchReserveBookings", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchReserveBookingsRequestBody Body;
        
        public fetchReserveBookingsRequest() {
        }
        
        public fetchReserveBookingsRequest(FriskisSvettisLib.PastellWebService.fetchReserveBookingsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchReserveBookingsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string key;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string revision;
        
        public fetchReserveBookingsRequestBody() {
        }
        
        public fetchReserveBookingsRequestBody(string key, string guid, string username, string password, string date, string revision) {
            this.key = key;
            this.guid = guid;
            this.username = username;
            this.password = password;
            this.date = date;
            this.revision = revision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchReserveBookingsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchReserveBookingsResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchReserveBookingsResponseBody Body;
        
        public fetchReserveBookingsResponse() {
        }
        
        public fetchReserveBookingsResponse(FriskisSvettisLib.PastellWebService.fetchReserveBookingsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchReserveBookingsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fetchReserveBookingsResult;
        
        public fetchReserveBookingsResponseBody() {
        }
        
        public fetchReserveBookingsResponseBody(string fetchReserveBookingsResult) {
            this.fetchReserveBookingsResult = fetchReserveBookingsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchBOSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchBOS", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchBOSRequestBody Body;
        
        public fetchBOSRequest() {
        }
        
        public fetchBOSRequest(FriskisSvettisLib.PastellWebService.fetchBOSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchBOSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string selecteddate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        public fetchBOSRequestBody() {
        }
        
        public fetchBOSRequestBody(string guid, string selecteddate, string user, string password) {
            this.guid = guid;
            this.selecteddate = selecteddate;
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchBOSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchBOSResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchBOSResponseBody Body;
        
        public fetchBOSResponse() {
        }
        
        public fetchBOSResponse(FriskisSvettisLib.PastellWebService.fetchBOSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchBOSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fetchBOSResult;
        
        public fetchBOSResponseBody() {
        }
        
        public fetchBOSResponseBody(string fetchBOSResult) {
            this.fetchBOSResult = fetchBOSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchBOSPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchBOSPage", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchBOSPageRequestBody Body;
        
        public fetchBOSPageRequest() {
        }
        
        public fetchBOSPageRequest(FriskisSvettisLib.PastellWebService.fetchBOSPageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchBOSPageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string date;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int page;
        
        public fetchBOSPageRequestBody() {
        }
        
        public fetchBOSPageRequestBody(string guid, string date, string user, string password, int page) {
            this.guid = guid;
            this.date = date;
            this.user = user;
            this.password = password;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchBOSPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchBOSPageResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchBOSPageResponseBody Body;
        
        public fetchBOSPageResponse() {
        }
        
        public fetchBOSPageResponse(FriskisSvettisLib.PastellWebService.fetchBOSPageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchBOSPageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fetchBOSPageResult;
        
        public fetchBOSPageResponseBody() {
        }
        
        public fetchBOSPageResponseBody(string fetchBOSPageResult) {
            this.fetchBOSPageResult = fetchBOSPageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchBOSGidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchBOSGid", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchBOSGidRequestBody Body;
        
        public fetchBOSGidRequest() {
        }
        
        public fetchBOSGidRequest(FriskisSvettisLib.PastellWebService.fetchBOSGidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchBOSGidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string selecteddate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string globalunit;
        
        public fetchBOSGidRequestBody() {
        }
        
        public fetchBOSGidRequestBody(string guid, string selecteddate, string user, string password, string globalunit) {
            this.guid = guid;
            this.selecteddate = selecteddate;
            this.user = user;
            this.password = password;
            this.globalunit = globalunit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchBOSGidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchBOSGidResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchBOSGidResponseBody Body;
        
        public fetchBOSGidResponse() {
        }
        
        public fetchBOSGidResponse(FriskisSvettisLib.PastellWebService.fetchBOSGidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchBOSGidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fetchBOSGidResult;
        
        public fetchBOSGidResponseBody() {
        }
        
        public fetchBOSGidResponseBody(string fetchBOSGidResult) {
            this.fetchBOSGidResult = fetchBOSGidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchBOSGidPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchBOSGidPage", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchBOSGidPageRequestBody Body;
        
        public fetchBOSGidPageRequest() {
        }
        
        public fetchBOSGidPageRequest(FriskisSvettisLib.PastellWebService.fetchBOSGidPageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchBOSGidPageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string guid;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string selecteddate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string globalunit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int page;
        
        public fetchBOSGidPageRequestBody() {
        }
        
        public fetchBOSGidPageRequestBody(string guid, string selecteddate, string user, string password, string globalunit, int page) {
            this.guid = guid;
            this.selecteddate = selecteddate;
            this.user = user;
            this.password = password;
            this.globalunit = globalunit;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchBOSGidPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchBOSGidPageResponse", Namespace="http://tempuri.org/", Order=0)]
        public FriskisSvettisLib.PastellWebService.fetchBOSGidPageResponseBody Body;
        
        public fetchBOSGidPageResponse() {
        }
        
        public fetchBOSGidPageResponse(FriskisSvettisLib.PastellWebService.fetchBOSGidPageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fetchBOSGidPageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fetchBOSGidPageResult;
        
        public fetchBOSGidPageResponseBody() {
        }
        
        public fetchBOSGidPageResponseBody(string fetchBOSGidPageResult) {
            this.fetchBOSGidPageResult = fetchBOSGidPageResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MobileServicesSoapChannel : FriskisSvettisLib.PastellWebService.MobileServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MobileServicesSoapClient : System.ServiceModel.ClientBase<FriskisSvettisLib.PastellWebService.MobileServicesSoap>, FriskisSvettisLib.PastellWebService.MobileServicesSoap {
        
        public MobileServicesSoapClient() {
        }
        
        public MobileServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MobileServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MobileServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.versionResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.version(FriskisSvettisLib.PastellWebService.versionRequest request) {
            return base.Channel.version(request);
        }
        
        public string version(string xml) {
            FriskisSvettisLib.PastellWebService.versionRequest inValue = new FriskisSvettisLib.PastellWebService.versionRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.versionRequestBody();
            inValue.Body.xml = xml;
            FriskisSvettisLib.PastellWebService.versionResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).version(inValue);
            return retVal.Body.versionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.processResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.process(FriskisSvettisLib.PastellWebService.processRequest request) {
            return base.Channel.process(request);
        }
        
        public string process(string xml) {
            FriskisSvettisLib.PastellWebService.processRequest inValue = new FriskisSvettisLib.PastellWebService.processRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.processRequestBody();
            inValue.Body.xml = xml;
            FriskisSvettisLib.PastellWebService.processResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).process(inValue);
            return retVal.Body.processResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.processUnsafeResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.processUnsafe(FriskisSvettisLib.PastellWebService.processUnsafeRequest request) {
            return base.Channel.processUnsafe(request);
        }
        
        public string processUnsafe(string xml) {
            FriskisSvettisLib.PastellWebService.processUnsafeRequest inValue = new FriskisSvettisLib.PastellWebService.processUnsafeRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.processUnsafeRequestBody();
            inValue.Body.xml = xml;
            FriskisSvettisLib.PastellWebService.processUnsafeResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).processUnsafe(inValue);
            return retVal.Body.processUnsafeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.loginResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.login(FriskisSvettisLib.PastellWebService.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string key, string globalunit, string username, string password, string revision) {
            FriskisSvettisLib.PastellWebService.loginRequest inValue = new FriskisSvettisLib.PastellWebService.loginRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.loginRequestBody();
            inValue.Body.key = key;
            inValue.Body.globalunit = globalunit;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.revision = revision;
            FriskisSvettisLib.PastellWebService.loginResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.bookReserveResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.bookReserve(FriskisSvettisLib.PastellWebService.bookReserveRequest request) {
            return base.Channel.bookReserve(request);
        }
        
        public string bookReserve(string key, string guid, string username, string password, string boid, string revision) {
            FriskisSvettisLib.PastellWebService.bookReserveRequest inValue = new FriskisSvettisLib.PastellWebService.bookReserveRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.bookReserveRequestBody();
            inValue.Body.key = key;
            inValue.Body.guid = guid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.boid = boid;
            inValue.Body.revision = revision;
            FriskisSvettisLib.PastellWebService.bookReserveResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).bookReserve(inValue);
            return retVal.Body.bookReserveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.debookReserveResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.debookReserve(FriskisSvettisLib.PastellWebService.debookReserveRequest request) {
            return base.Channel.debookReserve(request);
        }
        
        public string debookReserve(string key, string guid, string username, string password, string reservbid, string revision) {
            FriskisSvettisLib.PastellWebService.debookReserveRequest inValue = new FriskisSvettisLib.PastellWebService.debookReserveRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.debookReserveRequestBody();
            inValue.Body.key = key;
            inValue.Body.guid = guid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.reservbid = reservbid;
            inValue.Body.revision = revision;
            FriskisSvettisLib.PastellWebService.debookReserveResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).debookReserve(inValue);
            return retVal.Body.debookReserveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.bookResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.book(FriskisSvettisLib.PastellWebService.bookRequest request) {
            return base.Channel.book(request);
        }
        
        public string book(string key, string guid, string username, string password, string boid, string revision) {
            FriskisSvettisLib.PastellWebService.bookRequest inValue = new FriskisSvettisLib.PastellWebService.bookRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.bookRequestBody();
            inValue.Body.key = key;
            inValue.Body.guid = guid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.boid = boid;
            inValue.Body.revision = revision;
            FriskisSvettisLib.PastellWebService.bookResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).book(inValue);
            return retVal.Body.bookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.debookResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.debook(FriskisSvettisLib.PastellWebService.debookRequest request) {
            return base.Channel.debook(request);
        }
        
        public string debook(string key, string guid, string username, string password, string bid, string revision) {
            FriskisSvettisLib.PastellWebService.debookRequest inValue = new FriskisSvettisLib.PastellWebService.debookRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.debookRequestBody();
            inValue.Body.key = key;
            inValue.Body.guid = guid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.bid = bid;
            inValue.Body.revision = revision;
            FriskisSvettisLib.PastellWebService.debookResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).debook(inValue);
            return retVal.Body.debookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.fetchbookingsResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.fetchbookings(FriskisSvettisLib.PastellWebService.fetchbookingsRequest request) {
            return base.Channel.fetchbookings(request);
        }
        
        public string fetchbookings(string key, string guid, string username, string password, string date, string revision) {
            FriskisSvettisLib.PastellWebService.fetchbookingsRequest inValue = new FriskisSvettisLib.PastellWebService.fetchbookingsRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.fetchbookingsRequestBody();
            inValue.Body.key = key;
            inValue.Body.guid = guid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.date = date;
            inValue.Body.revision = revision;
            FriskisSvettisLib.PastellWebService.fetchbookingsResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).fetchbookings(inValue);
            return retVal.Body.fetchbookingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.fetchReserveBookingsResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.fetchReserveBookings(FriskisSvettisLib.PastellWebService.fetchReserveBookingsRequest request) {
            return base.Channel.fetchReserveBookings(request);
        }
        
        public string fetchReserveBookings(string key, string guid, string username, string password, string date, string revision) {
            FriskisSvettisLib.PastellWebService.fetchReserveBookingsRequest inValue = new FriskisSvettisLib.PastellWebService.fetchReserveBookingsRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.fetchReserveBookingsRequestBody();
            inValue.Body.key = key;
            inValue.Body.guid = guid;
            inValue.Body.username = username;
            inValue.Body.password = password;
            inValue.Body.date = date;
            inValue.Body.revision = revision;
            FriskisSvettisLib.PastellWebService.fetchReserveBookingsResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).fetchReserveBookings(inValue);
            return retVal.Body.fetchReserveBookingsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.fetchBOSResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.fetchBOS(FriskisSvettisLib.PastellWebService.fetchBOSRequest request) {
            return base.Channel.fetchBOS(request);
        }
        
        public string fetchBOS(string guid, string selecteddate, string user, string password) {
            FriskisSvettisLib.PastellWebService.fetchBOSRequest inValue = new FriskisSvettisLib.PastellWebService.fetchBOSRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.fetchBOSRequestBody();
            inValue.Body.guid = guid;
            inValue.Body.selecteddate = selecteddate;
            inValue.Body.user = user;
            inValue.Body.password = password;
            FriskisSvettisLib.PastellWebService.fetchBOSResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).fetchBOS(inValue);
            return retVal.Body.fetchBOSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.fetchBOSPageResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.fetchBOSPage(FriskisSvettisLib.PastellWebService.fetchBOSPageRequest request) {
            return base.Channel.fetchBOSPage(request);
        }
        
        public string fetchBOSPage(string guid, string date, string user, string password, int page) {
            FriskisSvettisLib.PastellWebService.fetchBOSPageRequest inValue = new FriskisSvettisLib.PastellWebService.fetchBOSPageRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.fetchBOSPageRequestBody();
            inValue.Body.guid = guid;
            inValue.Body.date = date;
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.page = page;
            FriskisSvettisLib.PastellWebService.fetchBOSPageResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).fetchBOSPage(inValue);
            return retVal.Body.fetchBOSPageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.fetchBOSGidResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.fetchBOSGid(FriskisSvettisLib.PastellWebService.fetchBOSGidRequest request) {
            return base.Channel.fetchBOSGid(request);
        }
        
        public string fetchBOSGid(string guid, string selecteddate, string user, string password, string globalunit) {
            FriskisSvettisLib.PastellWebService.fetchBOSGidRequest inValue = new FriskisSvettisLib.PastellWebService.fetchBOSGidRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.fetchBOSGidRequestBody();
            inValue.Body.guid = guid;
            inValue.Body.selecteddate = selecteddate;
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.globalunit = globalunit;
            FriskisSvettisLib.PastellWebService.fetchBOSGidResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).fetchBOSGid(inValue);
            return retVal.Body.fetchBOSGidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FriskisSvettisLib.PastellWebService.fetchBOSGidPageResponse FriskisSvettisLib.PastellWebService.MobileServicesSoap.fetchBOSGidPage(FriskisSvettisLib.PastellWebService.fetchBOSGidPageRequest request) {
            return base.Channel.fetchBOSGidPage(request);
        }
        
        public string fetchBOSGidPage(string guid, string selecteddate, string user, string password, string globalunit, int page) {
            FriskisSvettisLib.PastellWebService.fetchBOSGidPageRequest inValue = new FriskisSvettisLib.PastellWebService.fetchBOSGidPageRequest();
            inValue.Body = new FriskisSvettisLib.PastellWebService.fetchBOSGidPageRequestBody();
            inValue.Body.guid = guid;
            inValue.Body.selecteddate = selecteddate;
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.globalunit = globalunit;
            inValue.Body.page = page;
            FriskisSvettisLib.PastellWebService.fetchBOSGidPageResponse retVal = ((FriskisSvettisLib.PastellWebService.MobileServicesSoap)(this)).fetchBOSGidPage(inValue);
            return retVal.Body.fetchBOSGidPageResult;
        }
    }
}
